INSERT INTO `_role` (`id`, `nama`) VALUES
(1, 'SA');

INSERT INTO `_login` (`id`, `u53r`, `p455`, `nama`, `email`, `uk`, `id_role`, `active`, `pic`) VALUES
(1, 'admin', 'c1d2043aefe2e508fa6afd6f5825869d', 'Ok bos', 'eddy.tungadi@poliupg.ac.id','joyway', 1, 1, 'assets/images/avatar.png');

INSERT INTO `_fa5` (`id`, `nama`, `class`, `unicode`, `kategori`) VALUES
(1, 'Ad', 'fas fa-ad', 'f641', 'solid'),
(2, 'Address Book', 'fas fa-address-book', 'f2b9', 'solid'),
(3, 'Address Card', 'fas fa-address-card', 'f2bb', 'solid'),
(4, 'Adjust', 'fas fa-adjust', 'f042', 'solid'),
(5, 'Air Freshener', 'fas fa-air-freshener', 'f5d0', 'solid'),
(6, 'Align Center', 'fas fa-align-center', 'f037', 'solid'),
(7, 'Align Justify', 'fas fa-align-justify', 'f039', 'solid'),
(8, 'Align Left', 'fas fa-align-left', 'f036', 'solid'),
(9, 'Align Right', 'fas fa-align-right', 'f038', 'solid'),
(10, 'Allergies', 'fas fa-allergies', 'f461', 'solid'),
(11, 'Ambulance', 'fas fa-ambulance', 'f0f9', 'solid'),
(12, 'American Sign Language Interpreting', 'fas fa-american-sign-language-interpreting', 'f2a3', 'solid'),
(13, 'Anchor', 'fas fa-anchor', 'f13d', 'solid'),
(14, 'Angle Double Down', 'fas fa-angle-double-down', 'f103', 'solid'),
(15, 'Angle Double Left', 'fas fa-angle-double-left', 'f100', 'solid'),
(16, 'Angle Double Right', 'fas fa-angle-double-right', 'f101', 'solid'),
(17, 'Angle Double Up', 'fas fa-angle-double-up', 'f102', 'solid'),
(18, 'Angle Down', 'fas fa-angle-down', 'f107', 'solid'),
(19, 'Angle Left', 'fas fa-angle-left', 'f104', 'solid'),
(20, 'Angle Right', 'fas fa-angle-right', 'f105', 'solid'),
(21, 'Angle Up', 'fas fa-angle-up', 'f106', 'solid'),
(22, 'Angry', 'fas fa-angry', 'f556', 'solid'),
(23, 'Ankh', 'fas fa-ankh', 'f644', 'solid'),
(24, 'Apple Alt', 'fas fa-apple-alt', 'f5d1', 'solid'),
(25, 'Archive', 'fas fa-archive', 'f187', 'solid'),
(26, 'Archway', 'fas fa-archway', 'f557', 'solid'),
(27, 'Arrow Alt Circle Down', 'fas fa-arrow-alt-circle-down', 'f358', 'solid'),
(28, 'Arrow Alt Circle Left', 'fas fa-arrow-alt-circle-left', 'f359', 'solid'),
(29, 'Arrow Alt Circle Right', 'fas fa-arrow-alt-circle-right', 'f35a', 'solid'),
(30, 'Arrow Alt Circle Up', 'fas fa-arrow-alt-circle-up', 'f35b', 'solid'),
(31, 'Arrow Circle Down', 'fas fa-arrow-circle-down', 'f0ab', 'solid'),
(32, 'Arrow Circle Left', 'fas fa-arrow-circle-left', 'f0a8', 'solid'),
(33, 'Arrow Circle Right', 'fas fa-arrow-circle-right', 'f0a9', 'solid'),
(34, 'Arrow Circle Up', 'fas fa-arrow-circle-up', 'f0aa', 'solid'),
(35, 'Arrow Down', 'fas fa-arrow-down', 'f063', 'solid'),
(36, 'Arrow Left', 'fas fa-arrow-left', 'f060', 'solid'),
(37, 'Arrow Right', 'fas fa-arrow-right', 'f061', 'solid'),
(38, 'Arrow Up', 'fas fa-arrow-up', 'f062', 'solid'),
(39, 'Arrows Alt', 'fas fa-arrows-alt', 'f0b2', 'solid'),
(40, 'Arrows Alt H', 'fas fa-arrows-alt-h', 'f337', 'solid'),
(41, 'Arrows Alt V', 'fas fa-arrows-alt-v', 'f338', 'solid'),
(42, 'Assistive Listening Systems', 'fas fa-assistive-listening-systems', 'f2a2', 'solid'),
(43, 'Asterisk', 'fas fa-asterisk', 'f069', 'solid'),
(44, 'At', 'fas fa-at', 'f1fa', 'solid'),
(45, 'Atlas', 'fas fa-atlas', 'f558', 'solid'),
(46, 'Atom', 'fas fa-atom', 'f5d2', 'solid'),
(47, 'Audio Description', 'fas fa-audio-description', 'f29e', 'solid'),
(48, 'Award', 'fas fa-award', 'f559', 'solid'),
(49, 'Baby', 'fas fa-baby', 'f77c', 'solid'),
(50, 'Baby Carriage', 'fas fa-baby-carriage', 'f77d', 'solid'),
(51, 'Backspace', 'fas fa-backspace', 'f55a', 'solid'),
(52, 'Backward', 'fas fa-backward', 'f04a', 'solid'),
(53, 'Bacon', 'fas fa-bacon', 'f7e5', 'solid'),
(54, 'Bacteria', 'fas fa-bacteria', 'e059', 'solid'),
(55, 'Bacterium', 'fas fa-bacterium', 'e05a', 'solid'),
(56, 'Bahai', 'fas fa-bahai', 'f666', 'solid'),
(57, 'Balance Scale', 'fas fa-balance-scale', 'f24e', 'solid'),
(58, 'Balance Scale Left', 'fas fa-balance-scale-left', 'f515', 'solid'),
(59, 'Balance Scale Right', 'fas fa-balance-scale-right', 'f516', 'solid'),
(60, 'Ban', 'fas fa-ban', 'f05e', 'solid'),
(61, 'Band Aid', 'fas fa-band-aid', 'f462', 'solid'),
(62, 'Barcode', 'fas fa-barcode', 'f02a', 'solid'),
(63, 'Bars', 'fas fa-bars', 'f0c9', 'solid'),
(64, 'Baseball Ball', 'fas fa-baseball-ball', 'f433', 'solid'),
(65, 'Basketball Ball', 'fas fa-basketball-ball', 'f434', 'solid'),
(66, 'Bath', 'fas fa-bath', 'f2cd', 'solid'),
(67, 'Battery Empty', 'fas fa-battery-empty', 'f244', 'solid'),
(68, 'Battery Full', 'fas fa-battery-full', 'f240', 'solid'),
(69, 'Battery Half', 'fas fa-battery-half', 'f242', 'solid'),
(70, 'Battery Quarter', 'fas fa-battery-quarter', 'f243', 'solid'),
(71, 'Battery Three Quarters', 'fas fa-battery-three-quarters', 'f241', 'solid'),
(72, 'Bed', 'fas fa-bed', 'f236', 'solid'),
(73, 'Beer', 'fas fa-beer', 'f0fc', 'solid'),
(74, 'Bell', 'fas fa-bell', 'f0f3', 'solid'),
(75, 'Bell Slash', 'fas fa-bell-slash', 'f1f6', 'solid'),
(76, 'Bezier Curve', 'fas fa-bezier-curve', 'f55b', 'solid'),
(77, 'Bible', 'fas fa-bible', 'f647', 'solid'),
(78, 'Bicycle', 'fas fa-bicycle', 'f206', 'solid'),
(79, 'Biking', 'fas fa-biking', 'f84a', 'solid'),
(80, 'Binoculars', 'fas fa-binoculars', 'f1e5', 'solid'),
(81, 'Biohazard', 'fas fa-biohazard', 'f780', 'solid'),
(82, 'Birthday Cake', 'fas fa-birthday-cake', 'f1fd', 'solid'),
(83, 'Blender', 'fas fa-blender', 'f517', 'solid'),
(84, 'Blender Phone', 'fas fa-blender-phone', 'f6b6', 'solid'),
(85, 'Blind', 'fas fa-blind', 'f29d', 'solid'),
(86, 'Blog', 'fas fa-blog', 'f781', 'solid'),
(87, 'Bold', 'fas fa-bold', 'f032', 'solid'),
(88, 'Bolt', 'fas fa-bolt', 'f0e7', 'solid'),
(89, 'Bomb', 'fas fa-bomb', 'f1e2', 'solid'),
(90, 'Bone', 'fas fa-bone', 'f5d7', 'solid'),
(91, 'Bong', 'fas fa-bong', 'f55c', 'solid'),
(92, 'Book', 'fas fa-book', 'f02d', 'solid'),
(93, 'Book Dead', 'fas fa-book-dead', 'f6b7', 'solid'),
(94, 'Book Medical', 'fas fa-book-medical', 'f7e6', 'solid'),
(95, 'Book Open', 'fas fa-book-open', 'f518', 'solid'),
(96, 'Book Reader', 'fas fa-book-reader', 'f5da', 'solid'),
(97, 'Bookmark', 'fas fa-bookmark', 'f02e', 'solid'),
(98, 'Border All', 'fas fa-border-all', 'f84c', 'solid'),
(99, 'Border None', 'fas fa-border-none', 'f850', 'solid'),
(100, 'Border Style', 'fas fa-border-style', 'f853', 'solid'),
(101, 'Bowling Ball', 'fas fa-bowling-ball', 'f436', 'solid'),
(102, 'Box', 'fas fa-box', 'f466', 'solid'),
(103, 'Box Open', 'fas fa-box-open', 'f49e', 'solid'),
(104, 'Box Tissue', 'fas fa-box-tissue', 'e05b', 'solid'),
(105, 'Boxes', 'fas fa-boxes', 'f468', 'solid'),
(106, 'Braille', 'fas fa-braille', 'f2a1', 'solid'),
(107, 'Brain', 'fas fa-brain', 'f5dc', 'solid'),
(108, 'Bread Slice', 'fas fa-bread-slice', 'f7ec', 'solid'),
(109, 'Briefcase', 'fas fa-briefcase', 'f0b1', 'solid'),
(110, 'Briefcase Medical', 'fas fa-briefcase-medical', 'f469', 'solid'),
(111, 'Broadcast Tower', 'fas fa-broadcast-tower', 'f519', 'solid'),
(112, 'Broom', 'fas fa-broom', 'f51a', 'solid'),
(113, 'Brush', 'fas fa-brush', 'f55d', 'solid'),
(114, 'Bug', 'fas fa-bug', 'f188', 'solid'),
(115, 'Building', 'fas fa-building', 'f1ad', 'solid'),
(116, 'Bullhorn', 'fas fa-bullhorn', 'f0a1', 'solid'),
(117, 'Bullseye', 'fas fa-bullseye', 'f140', 'solid'),
(118, 'Burn', 'fas fa-burn', 'f46a', 'solid'),
(119, 'Bus', 'fas fa-bus', 'f207', 'solid'),
(120, 'Bus Alt', 'fas fa-bus-alt', 'f55e', 'solid'),
(121, 'Business Time', 'fas fa-business-time', 'f64a', 'solid'),
(122, 'Calculator', 'fas fa-calculator', 'f1ec', 'solid'),
(123, 'Calendar', 'fas fa-calendar', 'f133', 'solid'),
(124, 'Calendar Alt', 'fas fa-calendar-alt', 'f073', 'solid'),
(125, 'Calendar Check', 'fas fa-calendar-check', 'f274', 'solid'),
(126, 'Calendar Day', 'fas fa-calendar-day', 'f783', 'solid'),
(127, 'Calendar Minus', 'fas fa-calendar-minus', 'f272', 'solid'),
(128, 'Calendar Plus', 'fas fa-calendar-plus', 'f271', 'solid'),
(129, 'Calendar Times', 'fas fa-calendar-times', 'f273', 'solid'),
(130, 'Calendar Week', 'fas fa-calendar-week', 'f784', 'solid'),
(131, 'Camera', 'fas fa-camera', 'f030', 'solid'),
(132, 'Camera Retro', 'fas fa-camera-retro', 'f083', 'solid'),
(133, 'Campground', 'fas fa-campground', 'f6bb', 'solid'),
(134, 'Candy Cane', 'fas fa-candy-cane', 'f786', 'solid'),
(135, 'Cannabis', 'fas fa-cannabis', 'f55f', 'solid'),
(136, 'Capsules', 'fas fa-capsules', 'f46b', 'solid'),
(137, 'Car', 'fas fa-car', 'f1b9', 'solid'),
(138, 'Car Alt', 'fas fa-car-alt', 'f5de', 'solid'),
(139, 'Car Battery', 'fas fa-car-battery', 'f5df', 'solid'),
(140, 'Car Crash', 'fas fa-car-crash', 'f5e1', 'solid'),
(141, 'Car Side', 'fas fa-car-side', 'f5e4', 'solid'),
(142, 'Caravan', 'fas fa-caravan', 'f8ff', 'solid'),
(143, 'Caret Down', 'fas fa-caret-down', 'f0d7', 'solid'),
(144, 'Caret Left', 'fas fa-caret-left', 'f0d9', 'solid'),
(145, 'Caret Right', 'fas fa-caret-right', 'f0da', 'solid'),
(146, 'Caret Square Down', 'fas fa-caret-square-down', 'f150', 'solid'),
(147, 'Caret Square Left', 'fas fa-caret-square-left', 'f191', 'solid'),
(148, 'Caret Square Right', 'fas fa-caret-square-right', 'f152', 'solid'),
(149, 'Caret Square Up', 'fas fa-caret-square-up', 'f151', 'solid'),
(150, 'Caret Up', 'fas fa-caret-up', 'f0d8', 'solid'),
(151, 'Carrot', 'fas fa-carrot', 'f787', 'solid'),
(152, 'Cart Arrow Down', 'fas fa-cart-arrow-down', 'f218', 'solid'),
(153, 'Cart Plus', 'fas fa-cart-plus', 'f217', 'solid'),
(154, 'Cash Register', 'fas fa-cash-register', 'f788', 'solid'),
(155, 'Cat', 'fas fa-cat', 'f6be', 'solid'),
(156, 'Certificate', 'fas fa-certificate', 'f0a3', 'solid'),
(157, 'Chair', 'fas fa-chair', 'f6c0', 'solid'),
(158, 'Chalkboard', 'fas fa-chalkboard', 'f51b', 'solid'),
(159, 'Chalkboard Teacher', 'fas fa-chalkboard-teacher', 'f51c', 'solid'),
(160, 'Charging Station', 'fas fa-charging-station', 'f5e7', 'solid'),
(161, 'Chart Area', 'fas fa-chart-area', 'f1fe', 'solid'),
(162, 'Chart Bar', 'fas fa-chart-bar', 'f080', 'solid'),
(163, 'Chart Line', 'fas fa-chart-line', 'f201', 'solid'),
(164, 'Chart Pie', 'fas fa-chart-pie', 'f200', 'solid'),
(165, 'Check', 'fas fa-check', 'f00c', 'solid'),
(166, 'Check Circle', 'fas fa-check-circle', 'f058', 'solid'),
(167, 'Check Double', 'fas fa-check-double', 'f560', 'solid'),
(168, 'Check Square', 'fas fa-check-square', 'f14a', 'solid'),
(169, 'Cheese', 'fas fa-cheese', 'f7ef', 'solid'),
(170, 'Chess', 'fas fa-chess', 'f439', 'solid'),
(171, 'Chess Bishop', 'fas fa-chess-bishop', 'f43a', 'solid'),
(172, 'Chess Board', 'fas fa-chess-board', 'f43c', 'solid'),
(173, 'Chess King', 'fas fa-chess-king', 'f43f', 'solid'),
(174, 'Chess Knight', 'fas fa-chess-knight', 'f441', 'solid'),
(175, 'Chess Pawn', 'fas fa-chess-pawn', 'f443', 'solid'),
(176, 'Chess Queen', 'fas fa-chess-queen', 'f445', 'solid'),
(177, 'Chess Rook', 'fas fa-chess-rook', 'f447', 'solid'),
(178, 'Chevron Circle Down', 'fas fa-chevron-circle-down', 'f13a', 'solid'),
(179, 'Chevron Circle Left', 'fas fa-chevron-circle-left', 'f137', 'solid'),
(180, 'Chevron Circle Right', 'fas fa-chevron-circle-right', 'f138', 'solid'),
(181, 'Chevron Circle Up', 'fas fa-chevron-circle-up', 'f139', 'solid'),
(182, 'Chevron Down', 'fas fa-chevron-down', 'f078', 'solid'),
(183, 'Chevron Left', 'fas fa-chevron-left', 'f053', 'solid'),
(184, 'Chevron Right', 'fas fa-chevron-right', 'f054', 'solid'),
(185, 'Chevron Up', 'fas fa-chevron-up', 'f077', 'solid'),
(186, 'Child', 'fas fa-child', 'f1ae', 'solid'),
(187, 'Church', 'fas fa-church', 'f51d', 'solid'),
(188, 'Circle', 'fas fa-circle', 'f111', 'solid'),
(189, 'Circle Notch', 'fas fa-circle-notch', 'f1ce', 'solid'),
(190, 'City', 'fas fa-city', 'f64f', 'solid'),
(191, 'Clinic Medical', 'fas fa-clinic-medical', 'f7f2', 'solid'),
(192, 'Clipboard', 'fas fa-clipboard', 'f328', 'solid'),
(193, 'Clipboard Check', 'fas fa-clipboard-check', 'f46c', 'solid'),
(194, 'Clipboard List', 'fas fa-clipboard-list', 'f46d', 'solid'),
(195, 'Clock', 'fas fa-clock', 'f017', 'solid'),
(196, 'Clone', 'fas fa-clone', 'f24d', 'solid'),
(197, 'Closed Captioning', 'fas fa-closed-captioning', 'f20a', 'solid'),
(198, 'Cloud', 'fas fa-cloud', 'f0c2', 'solid'),
(199, 'Cloud Download Alt', 'fas fa-cloud-download-alt', 'f381', 'solid'),
(200, 'Cloud Meatball', 'fas fa-cloud-meatball', 'f73b', 'solid'),
(201, 'Cloud Moon', 'fas fa-cloud-moon', 'f6c3', 'solid'),
(202, 'Cloud Moon Rain', 'fas fa-cloud-moon-rain', 'f73c', 'solid'),
(203, 'Cloud Rain', 'fas fa-cloud-rain', 'f73d', 'solid'),
(204, 'Cloud Showers Heavy', 'fas fa-cloud-showers-heavy', 'f740', 'solid'),
(205, 'Cloud Sun', 'fas fa-cloud-sun', 'f6c4', 'solid'),
(206, 'Cloud Sun Rain', 'fas fa-cloud-sun-rain', 'f743', 'solid'),
(207, 'Cloud Upload Alt', 'fas fa-cloud-upload-alt', 'f382', 'solid'),
(208, 'Cocktail', 'fas fa-cocktail', 'f561', 'solid'),
(209, 'Code', 'fas fa-code', 'f121', 'solid'),
(210, 'Code Branch', 'fas fa-code-branch', 'f126', 'solid'),
(211, 'Coffee', 'fas fa-coffee', 'f0f4', 'solid'),
(212, 'Cog', 'fas fa-cog', 'f013', 'solid'),
(213, 'Cogs', 'fas fa-cogs', 'f085', 'solid'),
(214, 'Coins', 'fas fa-coins', 'f51e', 'solid'),
(215, 'Columns', 'fas fa-columns', 'f0db', 'solid'),
(216, 'Comment', 'fas fa-comment', 'f075', 'solid'),
(217, 'Comment Alt', 'fas fa-comment-alt', 'f27a', 'solid'),
(218, 'Comment Dollar', 'fas fa-comment-dollar', 'f651', 'solid'),
(219, 'Comment Dots', 'fas fa-comment-dots', 'f4ad', 'solid'),
(220, 'Comment Medical', 'fas fa-comment-medical', 'f7f5', 'solid'),
(221, 'Comment Slash', 'fas fa-comment-slash', 'f4b3', 'solid'),
(222, 'Comments', 'fas fa-comments', 'f086', 'solid'),
(223, 'Comments Dollar', 'fas fa-comments-dollar', 'f653', 'solid'),
(224, 'Compact Disc', 'fas fa-compact-disc', 'f51f', 'solid'),
(225, 'Compass', 'fas fa-compass', 'f14e', 'solid'),
(226, 'Compress', 'fas fa-compress', 'f066', 'solid'),
(227, 'Compress Alt', 'fas fa-compress-alt', 'f422', 'solid'),
(228, 'Compress Arrows Alt', 'fas fa-compress-arrows-alt', 'f78c', 'solid'),
(229, 'Concierge Bell', 'fas fa-concierge-bell', 'f562', 'solid'),
(230, 'Cookie', 'fas fa-cookie', 'f563', 'solid'),
(231, 'Cookie Bite', 'fas fa-cookie-bite', 'f564', 'solid'),
(232, 'Copy', 'fas fa-copy', 'f0c5', 'solid'),
(233, 'Copyright', 'fas fa-copyright', 'f1f9', 'solid'),
(234, 'Couch', 'fas fa-couch', 'f4b8', 'solid'),
(235, 'Credit Card', 'fas fa-credit-card', 'f09d', 'solid'),
(236, 'Crop', 'fas fa-crop', 'f125', 'solid'),
(237, 'Crop Alt', 'fas fa-crop-alt', 'f565', 'solid'),
(238, 'Cross', 'fas fa-cross', 'f654', 'solid'),
(239, 'Crosshairs', 'fas fa-crosshairs', 'f05b', 'solid'),
(240, 'Crow', 'fas fa-crow', 'f520', 'solid'),
(241, 'Crown', 'fas fa-crown', 'f521', 'solid'),
(242, 'Crutch', 'fas fa-crutch', 'f7f7', 'solid'),
(243, 'Cube', 'fas fa-cube', 'f1b2', 'solid'),
(244, 'Cubes', 'fas fa-cubes', 'f1b3', 'solid'),
(245, 'Cut', 'fas fa-cut', 'f0c4', 'solid'),
(246, 'Database', 'fas fa-database', 'f1c0', 'solid'),
(247, 'Deaf', 'fas fa-deaf', 'f2a4', 'solid'),
(248, 'Democrat', 'fas fa-democrat', 'f747', 'solid'),
(249, 'Desktop', 'fas fa-desktop', 'f108', 'solid'),
(250, 'Dharmachakra', 'fas fa-dharmachakra', 'f655', 'solid'),
(251, 'Diagnoses', 'fas fa-diagnoses', 'f470', 'solid'),
(252, 'Dice', 'fas fa-dice', 'f522', 'solid'),
(253, 'Dice D20', 'fas fa-dice-d20', 'f6cf', 'solid'),
(254, 'Dice D6', 'fas fa-dice-d6', 'f6d1', 'solid'),
(255, 'Dice Five', 'fas fa-dice-five', 'f523', 'solid'),
(256, 'Dice Four', 'fas fa-dice-four', 'f524', 'solid'),
(257, 'Dice One', 'fas fa-dice-one', 'f525', 'solid'),
(258, 'Dice Six', 'fas fa-dice-six', 'f526', 'solid'),
(259, 'Dice Three', 'fas fa-dice-three', 'f527', 'solid'),
(260, 'Dice Two', 'fas fa-dice-two', 'f528', 'solid'),
(261, 'Digital Tachograph', 'fas fa-digital-tachograph', 'f566', 'solid'),
(262, 'Directions', 'fas fa-directions', 'f5eb', 'solid'),
(263, 'Disease', 'fas fa-disease', 'f7fa', 'solid'),
(264, 'Divide', 'fas fa-divide', 'f529', 'solid'),
(265, 'Dizzy', 'fas fa-dizzy', 'f567', 'solid'),
(266, 'Dna', 'fas fa-dna', 'f471', 'solid'),
(267, 'Dog', 'fas fa-dog', 'f6d3', 'solid'),
(268, 'Dollar Sign', 'fas fa-dollar-sign', 'f155', 'solid'),
(269, 'Dolly', 'fas fa-dolly', 'f472', 'solid'),
(270, 'Dolly Flatbed', 'fas fa-dolly-flatbed', 'f474', 'solid'),
(271, 'Donate', 'fas fa-donate', 'f4b9', 'solid'),
(272, 'Door Closed', 'fas fa-door-closed', 'f52a', 'solid'),
(273, 'Door Open', 'fas fa-door-open', 'f52b', 'solid'),
(274, 'Dot Circle', 'fas fa-dot-circle', 'f192', 'solid'),
(275, 'Dove', 'fas fa-dove', 'f4ba', 'solid'),
(276, 'Download', 'fas fa-download', 'f019', 'solid'),
(277, 'Drafting Compass', 'fas fa-drafting-compass', 'f568', 'solid'),
(278, 'Dragon', 'fas fa-dragon', 'f6d5', 'solid'),
(279, 'Draw Polygon', 'fas fa-draw-polygon', 'f5ee', 'solid'),
(280, 'Drum', 'fas fa-drum', 'f569', 'solid'),
(281, 'Drum Steelpan', 'fas fa-drum-steelpan', 'f56a', 'solid'),
(282, 'Drumstick Bite', 'fas fa-drumstick-bite', 'f6d7', 'solid'),
(283, 'Dumbbell', 'fas fa-dumbbell', 'f44b', 'solid'),
(284, 'Dumpster', 'fas fa-dumpster', 'f793', 'solid'),
(285, 'Dumpster Fire', 'fas fa-dumpster-fire', 'f794', 'solid'),
(286, 'Dungeon', 'fas fa-dungeon', 'f6d9', 'solid'),
(287, 'Edit', 'fas fa-edit', 'f044', 'solid'),
(288, 'Egg', 'fas fa-egg', 'f7fb', 'solid'),
(289, 'Eject', 'fas fa-eject', 'f052', 'solid'),
(290, 'Ellipsis H', 'fas fa-ellipsis-h', 'f141', 'solid'),
(291, 'Ellipsis V', 'fas fa-ellipsis-v', 'f142', 'solid'),
(292, 'Envelope', 'fas fa-envelope', 'f0e0', 'solid'),
(293, 'Envelope Open', 'fas fa-envelope-open', 'f2b6', 'solid'),
(294, 'Envelope Open Text', 'fas fa-envelope-open-text', 'f658', 'solid'),
(295, 'Envelope Square', 'fas fa-envelope-square', 'f199', 'solid'),
(296, 'Equals', 'fas fa-equals', 'f52c', 'solid'),
(297, 'Eraser', 'fas fa-eraser', 'f12d', 'solid'),
(298, 'Ethernet', 'fas fa-ethernet', 'f796', 'solid'),
(299, 'Euro Sign', 'fas fa-euro-sign', 'f153', 'solid'),
(300, 'Exchange Alt', 'fas fa-exchange-alt', 'f362', 'solid'),
(301, 'Exclamation', 'fas fa-exclamation', 'f12a', 'solid'),
(302, 'Exclamation Circle', 'fas fa-exclamation-circle', 'f06a', 'solid'),
(303, 'Exclamation Triangle', 'fas fa-exclamation-triangle', 'f071', 'solid'),
(304, 'Expand', 'fas fa-expand', 'f065', 'solid'),
(305, 'Expand Alt', 'fas fa-expand-alt', 'f424', 'solid'),
(306, 'Expand Arrows Alt', 'fas fa-expand-arrows-alt', 'f31e', 'solid'),
(307, 'External Link Alt', 'fas fa-external-link-alt', 'f35d', 'solid'),
(308, 'External Link Square Alt', 'fas fa-external-link-square-alt', 'f360', 'solid'),
(309, 'Eye', 'fas fa-eye', 'f06e', 'solid'),
(310, 'Eye Dropper', 'fas fa-eye-dropper', 'f1fb', 'solid'),
(311, 'Eye Slash', 'fas fa-eye-slash', 'f070', 'solid'),
(312, 'Fan', 'fas fa-fan', 'f863', 'solid'),
(313, 'Fast Backward', 'fas fa-fast-backward', 'f049', 'solid'),
(314, 'Fast Forward', 'fas fa-fast-forward', 'f050', 'solid'),
(315, 'Faucet', 'fas fa-faucet', 'e005', 'solid'),
(316, 'Fax', 'fas fa-fax', 'f1ac', 'solid'),
(317, 'Feather', 'fas fa-feather', 'f52d', 'solid'),
(318, 'Feather Alt', 'fas fa-feather-alt', 'f56b', 'solid'),
(319, 'Female', 'fas fa-female', 'f182', 'solid'),
(320, 'Fighter Jet', 'fas fa-fighter-jet', 'f0fb', 'solid'),
(321, 'File', 'fas fa-file', 'f15b', 'solid'),
(322, 'File Alt', 'fas fa-file-alt', 'f15c', 'solid'),
(323, 'File Archive', 'fas fa-file-archive', 'f1c6', 'solid'),
(324, 'File Audio', 'fas fa-file-audio', 'f1c7', 'solid'),
(325, 'File Code', 'fas fa-file-code', 'f1c9', 'solid'),
(326, 'File Contract', 'fas fa-file-contract', 'f56c', 'solid'),
(327, 'File Csv', 'fas fa-file-csv', 'f6dd', 'solid'),
(328, 'File Download', 'fas fa-file-download', 'f56d', 'solid'),
(329, 'File Excel', 'fas fa-file-excel', 'f1c3', 'solid'),
(330, 'File Export', 'fas fa-file-export', 'f56e', 'solid'),
(331, 'File Image', 'fas fa-file-image', 'f1c5', 'solid'),
(332, 'File Import', 'fas fa-file-import', 'f56f', 'solid'),
(333, 'File Invoice', 'fas fa-file-invoice', 'f570', 'solid'),
(334, 'File Invoice Dollar', 'fas fa-file-invoice-dollar', 'f571', 'solid'),
(335, 'File Medical', 'fas fa-file-medical', 'f477', 'solid'),
(336, 'File Medical Alt', 'fas fa-file-medical-alt', 'f478', 'solid'),
(337, 'File Pdf', 'fas fa-file-pdf', 'f1c1', 'solid'),
(338, 'File Powerpoint', 'fas fa-file-powerpoint', 'f1c4', 'solid'),
(339, 'File Prescription', 'fas fa-file-prescription', 'f572', 'solid'),
(340, 'File Signature', 'fas fa-file-signature', 'f573', 'solid'),
(341, 'File Upload', 'fas fa-file-upload', 'f574', 'solid'),
(342, 'File Video', 'fas fa-file-video', 'f1c8', 'solid'),
(343, 'File Word', 'fas fa-file-word', 'f1c2', 'solid'),
(344, 'Fill', 'fas fa-fill', 'f575', 'solid'),
(345, 'Fill Drip', 'fas fa-fill-drip', 'f576', 'solid'),
(346, 'Film', 'fas fa-film', 'f008', 'solid'),
(347, 'Filter', 'fas fa-filter', 'f0b0', 'solid'),
(348, 'Fingerprint', 'fas fa-fingerprint', 'f577', 'solid'),
(349, 'Fire', 'fas fa-fire', 'f06d', 'solid'),
(350, 'Fire Alt', 'fas fa-fire-alt', 'f7e4', 'solid'),
(351, 'Fire Extinguisher', 'fas fa-fire-extinguisher', 'f134', 'solid'),
(352, 'First Aid', 'fas fa-first-aid', 'f479', 'solid'),
(353, 'Fish', 'fas fa-fish', 'f578', 'solid'),
(354, 'Fist Raised', 'fas fa-fist-raised', 'f6de', 'solid'),
(355, 'Flag', 'fas fa-flag', 'f024', 'solid'),
(356, 'Flag Checkered', 'fas fa-flag-checkered', 'f11e', 'solid'),
(357, 'Flag Usa', 'fas fa-flag-usa', 'f74d', 'solid'),
(358, 'Flask', 'fas fa-flask', 'f0c3', 'solid'),
(359, 'Flushed', 'fas fa-flushed', 'f579', 'solid'),
(360, 'Folder', 'fas fa-folder', 'f07b', 'solid'),
(361, 'Folder Minus', 'fas fa-folder-minus', 'f65d', 'solid'),
(362, 'Folder Open', 'fas fa-folder-open', 'f07c', 'solid'),
(363, 'Folder Plus', 'fas fa-folder-plus', 'f65e', 'solid'),
(364, 'Font', 'fas fa-font', 'f031', 'solid'),
(365, 'Football Ball', 'fas fa-football-ball', 'f44e', 'solid'),
(366, 'Forward', 'fas fa-forward', 'f04e', 'solid'),
(367, 'Frog', 'fas fa-frog', 'f52e', 'solid'),
(368, 'Frown', 'fas fa-frown', 'f119', 'solid'),
(369, 'Frown Open', 'fas fa-frown-open', 'f57a', 'solid'),
(370, 'Funnel Dollar', 'fas fa-funnel-dollar', 'f662', 'solid'),
(371, 'Futbol', 'fas fa-futbol', 'f1e3', 'solid'),
(372, 'Gamepad', 'fas fa-gamepad', 'f11b', 'solid'),
(373, 'Gas Pump', 'fas fa-gas-pump', 'f52f', 'solid'),
(374, 'Gavel', 'fas fa-gavel', 'f0e3', 'solid'),
(375, 'Gem', 'fas fa-gem', 'f3a5', 'solid'),
(376, 'Genderless', 'fas fa-genderless', 'f22d', 'solid'),
(377, 'Ghost', 'fas fa-ghost', 'f6e2', 'solid'),
(378, 'Gift', 'fas fa-gift', 'f06b', 'solid'),
(379, 'Gifts', 'fas fa-gifts', 'f79c', 'solid'),
(380, 'Glass Cheers', 'fas fa-glass-cheers', 'f79f', 'solid'),
(381, 'Glass Martini', 'fas fa-glass-martini', 'f000', 'solid'),
(382, 'Glass Martini Alt', 'fas fa-glass-martini-alt', 'f57b', 'solid'),
(383, 'Glass Whiskey', 'fas fa-glass-whiskey', 'f7a0', 'solid'),
(384, 'Glasses', 'fas fa-glasses', 'f530', 'solid'),
(385, 'Globe', 'fas fa-globe', 'f0ac', 'solid'),
(386, 'Globe Africa', 'fas fa-globe-africa', 'f57c', 'solid'),
(387, 'Globe Americas', 'fas fa-globe-americas', 'f57d', 'solid'),
(388, 'Globe Asia', 'fas fa-globe-asia', 'f57e', 'solid'),
(389, 'Globe Europe', 'fas fa-globe-europe', 'f7a2', 'solid'),
(390, 'Golf Ball', 'fas fa-golf-ball', 'f450', 'solid'),
(391, 'Gopuram', 'fas fa-gopuram', 'f664', 'solid'),
(392, 'Graduation Cap', 'fas fa-graduation-cap', 'f19d', 'solid'),
(393, 'Greater Than', 'fas fa-greater-than', 'f531', 'solid'),
(394, 'Greater Than Equal', 'fas fa-greater-than-equal', 'f532', 'solid'),
(395, 'Grimace', 'fas fa-grimace', 'f57f', 'solid'),
(396, 'Grin', 'fas fa-grin', 'f580', 'solid'),
(397, 'Grin Alt', 'fas fa-grin-alt', 'f581', 'solid'),
(398, 'Grin Beam', 'fas fa-grin-beam', 'f582', 'solid'),
(399, 'Grin Beam Sweat', 'fas fa-grin-beam-sweat', 'f583', 'solid'),
(400, 'Grin Hearts', 'fas fa-grin-hearts', 'f584', 'solid'),
(401, 'Grin Squint', 'fas fa-grin-squint', 'f585', 'solid'),
(402, 'Grin Squint Tears', 'fas fa-grin-squint-tears', 'f586', 'solid'),
(403, 'Grin Stars', 'fas fa-grin-stars', 'f587', 'solid'),
(404, 'Grin Tears', 'fas fa-grin-tears', 'f588', 'solid'),
(405, 'Grin Tongue', 'fas fa-grin-tongue', 'f589', 'solid'),
(406, 'Grin Tongue Squint', 'fas fa-grin-tongue-squint', 'f58a', 'solid'),
(407, 'Grin Tongue Wink', 'fas fa-grin-tongue-wink', 'f58b', 'solid'),
(408, 'Grin Wink', 'fas fa-grin-wink', 'f58c', 'solid'),
(409, 'Grip Horizontal', 'fas fa-grip-horizontal', 'f58d', 'solid'),
(410, 'Grip Lines', 'fas fa-grip-lines', 'f7a4', 'solid'),
(411, 'Grip Lines Vertical', 'fas fa-grip-lines-vertical', 'f7a5', 'solid'),
(412, 'Grip Vertical', 'fas fa-grip-vertical', 'f58e', 'solid'),
(413, 'Guitar', 'fas fa-guitar', 'f7a6', 'solid'),
(414, 'H Square', 'fas fa-h-square', 'f0fd', 'solid'),
(415, 'Hamburger', 'fas fa-hamburger', 'f805', 'solid'),
(416, 'Hammer', 'fas fa-hammer', 'f6e3', 'solid'),
(417, 'Hamsa', 'fas fa-hamsa', 'f665', 'solid'),
(418, 'Hand Holding', 'fas fa-hand-holding', 'f4bd', 'solid'),
(419, 'Hand Holding Heart', 'fas fa-hand-holding-heart', 'f4be', 'solid'),
(420, 'Hand Holding Medical', 'fas fa-hand-holding-medical', 'e05c', 'solid'),
(421, 'Hand Holding Usd', 'fas fa-hand-holding-usd', 'f4c0', 'solid'),
(422, 'Hand Holding Water', 'fas fa-hand-holding-water', 'f4c1', 'solid'),
(423, 'Hand Lizard', 'fas fa-hand-lizard', 'f258', 'solid'),
(424, 'Hand Middle Finger', 'fas fa-hand-middle-finger', 'f806', 'solid'),
(425, 'Hand Paper', 'fas fa-hand-paper', 'f256', 'solid'),
(426, 'Hand Peace', 'fas fa-hand-peace', 'f25b', 'solid'),
(427, 'Hand Point Down', 'fas fa-hand-point-down', 'f0a7', 'solid'),
(428, 'Hand Point Left', 'fas fa-hand-point-left', 'f0a5', 'solid'),
(429, 'Hand Point Right', 'fas fa-hand-point-right', 'f0a4', 'solid'),
(430, 'Hand Point Up', 'fas fa-hand-point-up', 'f0a6', 'solid'),
(431, 'Hand Pointer', 'fas fa-hand-pointer', 'f25a', 'solid'),
(432, 'Hand Rock', 'fas fa-hand-rock', 'f255', 'solid'),
(433, 'Hand Scissors', 'fas fa-hand-scissors', 'f257', 'solid'),
(434, 'Hand Sparkles', 'fas fa-hand-sparkles', 'e05d', 'solid'),
(435, 'Hand Spock', 'fas fa-hand-spock', 'f259', 'solid'),
(436, 'Hands', 'fas fa-hands', 'f4c2', 'solid'),
(437, 'Hands Helping', 'fas fa-hands-helping', 'f4c4', 'solid'),
(438, 'Hands Wash', 'fas fa-hands-wash', 'e05e', 'solid'),
(439, 'Handshake', 'fas fa-handshake', 'f2b5', 'solid'),
(440, 'Handshake Alt Slash', 'fas fa-handshake-alt-slash', 'e05f', 'solid'),
(441, 'Handshake Slash', 'fas fa-handshake-slash', 'e060', 'solid'),
(442, 'Hanukiah', 'fas fa-hanukiah', 'f6e6', 'solid'),
(443, 'Hard Hat', 'fas fa-hard-hat', 'f807', 'solid'),
(444, 'Hashtag', 'fas fa-hashtag', 'f292', 'solid'),
(445, 'Hat Cowboy', 'fas fa-hat-cowboy', 'f8c0', 'solid'),
(446, 'Hat Cowboy Side', 'fas fa-hat-cowboy-side', 'f8c1', 'solid'),
(447, 'Hat Wizard', 'fas fa-hat-wizard', 'f6e8', 'solid'),
(448, 'Hdd', 'fas fa-hdd', 'f0a0', 'solid'),
(449, 'Head Side Cough', 'fas fa-head-side-cough', 'e061', 'solid'),
(450, 'Head Side Cough Slash', 'fas fa-head-side-cough-slash', 'e062', 'solid'),
(451, 'Head Side Mask', 'fas fa-head-side-mask', 'e063', 'solid'),
(452, 'Head Side Virus', 'fas fa-head-side-virus', 'e064', 'solid'),
(453, 'Heading', 'fas fa-heading', 'f1dc', 'solid'),
(454, 'Headphones', 'fas fa-headphones', 'f025', 'solid'),
(455, 'Headphones Alt', 'fas fa-headphones-alt', 'f58f', 'solid'),
(456, 'Headset', 'fas fa-headset', 'f590', 'solid'),
(457, 'Heart', 'fas fa-heart', 'f004', 'solid'),
(458, 'Heart Broken', 'fas fa-heart-broken', 'f7a9', 'solid'),
(459, 'Heartbeat', 'fas fa-heartbeat', 'f21e', 'solid'),
(460, 'Helicopter', 'fas fa-helicopter', 'f533', 'solid'),
(461, 'Highlighter', 'fas fa-highlighter', 'f591', 'solid'),
(462, 'Hiking', 'fas fa-hiking', 'f6ec', 'solid'),
(463, 'Hippo', 'fas fa-hippo', 'f6ed', 'solid'),
(464, 'History', 'fas fa-history', 'f1da', 'solid'),
(465, 'Hockey Puck', 'fas fa-hockey-puck', 'f453', 'solid'),
(466, 'Holly Berry', 'fas fa-holly-berry', 'f7aa', 'solid'),
(467, 'Home', 'fas fa-home', 'f015', 'solid'),
(468, 'Horse', 'fas fa-horse', 'f6f0', 'solid'),
(469, 'Horse Head', 'fas fa-horse-head', 'f7ab', 'solid'),
(470, 'Hospital', 'fas fa-hospital', 'f0f8', 'solid'),
(471, 'Hospital Alt', 'fas fa-hospital-alt', 'f47d', 'solid'),
(472, 'Hospital Symbol', 'fas fa-hospital-symbol', 'f47e', 'solid'),
(473, 'Hospital User', 'fas fa-hospital-user', 'f80d', 'solid'),
(474, 'Hot Tub', 'fas fa-hot-tub', 'f593', 'solid'),
(475, 'Hotdog', 'fas fa-hotdog', 'f80f', 'solid'),
(476, 'Hotel', 'fas fa-hotel', 'f594', 'solid'),
(477, 'Hourglass', 'fas fa-hourglass', 'f254', 'solid'),
(478, 'Hourglass End', 'fas fa-hourglass-end', 'f253', 'solid'),
(479, 'Hourglass Half', 'fas fa-hourglass-half', 'f252', 'solid'),
(480, 'Hourglass Start', 'fas fa-hourglass-start', 'f251', 'solid'),
(481, 'House Damage', 'fas fa-house-damage', 'f6f1', 'solid'),
(482, 'House User', 'fas fa-house-user', 'e065', 'solid'),
(483, 'Hryvnia', 'fas fa-hryvnia', 'f6f2', 'solid'),
(484, 'I Cursor', 'fas fa-i-cursor', 'f246', 'solid'),
(485, 'Ice Cream', 'fas fa-ice-cream', 'f810', 'solid'),
(486, 'Icicles', 'fas fa-icicles', 'f7ad', 'solid'),
(487, 'Icons', 'fas fa-icons', 'f86d', 'solid'),
(488, 'Id Badge', 'fas fa-id-badge', 'f2c1', 'solid'),
(489, 'Id Card', 'fas fa-id-card', 'f2c2', 'solid'),
(490, 'Id Card Alt', 'fas fa-id-card-alt', 'f47f', 'solid'),
(491, 'Igloo', 'fas fa-igloo', 'f7ae', 'solid'),
(492, 'Image', 'fas fa-image', 'f03e', 'solid'),
(493, 'Images', 'fas fa-images', 'f302', 'solid'),
(494, 'Inbox', 'fas fa-inbox', 'f01c', 'solid'),
(495, 'Indent', 'fas fa-indent', 'f03c', 'solid'),
(496, 'Industry', 'fas fa-industry', 'f275', 'solid'),
(497, 'Infinity', 'fas fa-infinity', 'f534', 'solid'),
(498, 'Info', 'fas fa-info', 'f129', 'solid'),
(499, 'Info Circle', 'fas fa-info-circle', 'f05a', 'solid'),
(500, 'Italic', 'fas fa-italic', 'f033', 'solid'),
(501, 'Jedi', 'fas fa-jedi', 'f669', 'solid'),
(502, 'Joint', 'fas fa-joint', 'f595', 'solid'),
(503, 'Journal Whills', 'fas fa-journal-whills', 'f66a', 'solid'),
(504, 'Kaaba', 'fas fa-kaaba', 'f66b', 'solid'),
(505, 'Key', 'fas fa-key', 'f084', 'solid'),
(506, 'Keyboard', 'fas fa-keyboard', 'f11c', 'solid'),
(507, 'Khanda', 'fas fa-khanda', 'f66d', 'solid'),
(508, 'Kiss', 'fas fa-kiss', 'f596', 'solid'),
(509, 'Kiss Beam', 'fas fa-kiss-beam', 'f597', 'solid'),
(510, 'Kiss Wink Heart', 'fas fa-kiss-wink-heart', 'f598', 'solid'),
(511, 'Kiwi Bird', 'fas fa-kiwi-bird', 'f535', 'solid'),
(512, 'Landmark', 'fas fa-landmark', 'f66f', 'solid'),
(513, 'Language', 'fas fa-language', 'f1ab', 'solid'),
(514, 'Laptop', 'fas fa-laptop', 'f109', 'solid'),
(515, 'Laptop Code', 'fas fa-laptop-code', 'f5fc', 'solid'),
(516, 'Laptop House', 'fas fa-laptop-house', 'e066', 'solid'),
(517, 'Laptop Medical', 'fas fa-laptop-medical', 'f812', 'solid'),
(518, 'Laugh', 'fas fa-laugh', 'f599', 'solid'),
(519, 'Laugh Beam', 'fas fa-laugh-beam', 'f59a', 'solid'),
(520, 'Laugh Squint', 'fas fa-laugh-squint', 'f59b', 'solid'),
(521, 'Laugh Wink', 'fas fa-laugh-wink', 'f59c', 'solid'),
(522, 'Layer Group', 'fas fa-layer-group', 'f5fd', 'solid'),
(523, 'Leaf', 'fas fa-leaf', 'f06c', 'solid'),
(524, 'Lemon', 'fas fa-lemon', 'f094', 'solid'),
(525, 'Less Than', 'fas fa-less-than', 'f536', 'solid'),
(526, 'Less Than Equal', 'fas fa-less-than-equal', 'f537', 'solid'),
(527, 'Level Down Alt', 'fas fa-level-down-alt', 'f3be', 'solid'),
(528, 'Level Up Alt', 'fas fa-level-up-alt', 'f3bf', 'solid'),
(529, 'Life Ring', 'fas fa-life-ring', 'f1cd', 'solid'),
(530, 'Lightbulb', 'fas fa-lightbulb', 'f0eb', 'solid'),
(531, 'Link', 'fas fa-link', 'f0c1', 'solid'),
(532, 'Lira Sign', 'fas fa-lira-sign', 'f195', 'solid'),
(533, 'List', 'fas fa-list', 'f03a', 'solid'),
(534, 'List Alt', 'fas fa-list-alt', 'f022', 'solid'),
(535, 'List Ol', 'fas fa-list-ol', 'f0cb', 'solid'),
(536, 'List Ul', 'fas fa-list-ul', 'f0ca', 'solid'),
(537, 'Location Arrow', 'fas fa-location-arrow', 'f124', 'solid'),
(538, 'Lock', 'fas fa-lock', 'f023', 'solid'),
(539, 'Lock Open', 'fas fa-lock-open', 'f3c1', 'solid'),
(540, 'Long Arrow Alt Down', 'fas fa-long-arrow-alt-down', 'f309', 'solid'),
(541, 'Long Arrow Alt Left', 'fas fa-long-arrow-alt-left', 'f30a', 'solid'),
(542, 'Long Arrow Alt Right', 'fas fa-long-arrow-alt-right', 'f30b', 'solid'),
(543, 'Long Arrow Alt Up', 'fas fa-long-arrow-alt-up', 'f30c', 'solid'),
(544, 'Low Vision', 'fas fa-low-vision', 'f2a8', 'solid'),
(545, 'Luggage Cart', 'fas fa-luggage-cart', 'f59d', 'solid'),
(546, 'Lungs', 'fas fa-lungs', 'f604', 'solid'),
(547, 'Lungs Virus', 'fas fa-lungs-virus', 'e067', 'solid'),
(548, 'Magic', 'fas fa-magic', 'f0d0', 'solid'),
(549, 'Magnet', 'fas fa-magnet', 'f076', 'solid'),
(550, 'Mail Bulk', 'fas fa-mail-bulk', 'f674', 'solid'),
(551, 'Male', 'fas fa-male', 'f183', 'solid'),
(552, 'Map', 'fas fa-map', 'f279', 'solid'),
(553, 'Map Marked', 'fas fa-map-marked', 'f59f', 'solid'),
(554, 'Map Marked Alt', 'fas fa-map-marked-alt', 'f5a0', 'solid'),
(555, 'Map Marker', 'fas fa-map-marker', 'f041', 'solid'),
(556, 'Map Marker Alt', 'fas fa-map-marker-alt', 'f3c5', 'solid'),
(557, 'Map Pin', 'fas fa-map-pin', 'f276', 'solid'),
(558, 'Map Signs', 'fas fa-map-signs', 'f277', 'solid'),
(559, 'Marker', 'fas fa-marker', 'f5a1', 'solid'),
(560, 'Mars', 'fas fa-mars', 'f222', 'solid'),
(561, 'Mars Double', 'fas fa-mars-double', 'f227', 'solid'),
(562, 'Mars Stroke', 'fas fa-mars-stroke', 'f229', 'solid'),
(563, 'Mars Stroke H', 'fas fa-mars-stroke-h', 'f22b', 'solid'),
(564, 'Mars Stroke V', 'fas fa-mars-stroke-v', 'f22a', 'solid'),
(565, 'Mask', 'fas fa-mask', 'f6fa', 'solid'),
(566, 'Medal', 'fas fa-medal', 'f5a2', 'solid'),
(567, 'Medkit', 'fas fa-medkit', 'f0fa', 'solid'),
(568, 'Meh', 'fas fa-meh', 'f11a', 'solid'),
(569, 'Meh Blank', 'fas fa-meh-blank', 'f5a4', 'solid'),
(570, 'Meh Rolling Eyes', 'fas fa-meh-rolling-eyes', 'f5a5', 'solid'),
(571, 'Memory', 'fas fa-memory', 'f538', 'solid'),
(572, 'Menorah', 'fas fa-menorah', 'f676', 'solid'),
(573, 'Mercury', 'fas fa-mercury', 'f223', 'solid'),
(574, 'Meteor', 'fas fa-meteor', 'f753', 'solid'),
(575, 'Microchip', 'fas fa-microchip', 'f2db', 'solid'),
(576, 'Microphone', 'fas fa-microphone', 'f130', 'solid'),
(577, 'Microphone Alt', 'fas fa-microphone-alt', 'f3c9', 'solid'),
(578, 'Microphone Alt Slash', 'fas fa-microphone-alt-slash', 'f539', 'solid'),
(579, 'Microphone Slash', 'fas fa-microphone-slash', 'f131', 'solid'),
(580, 'Microscope', 'fas fa-microscope', 'f610', 'solid'),
(581, 'Minus', 'fas fa-minus', 'f068', 'solid'),
(582, 'Minus Circle', 'fas fa-minus-circle', 'f056', 'solid'),
(583, 'Minus Square', 'fas fa-minus-square', 'f146', 'solid'),
(584, 'Mitten', 'fas fa-mitten', 'f7b5', 'solid'),
(585, 'Mobile', 'fas fa-mobile', 'f10b', 'solid'),
(586, 'Mobile Alt', 'fas fa-mobile-alt', 'f3cd', 'solid'),
(587, 'Money Bill', 'fas fa-money-bill', 'f0d6', 'solid'),
(588, 'Money Bill Alt', 'fas fa-money-bill-alt', 'f3d1', 'solid'),
(589, 'Money Bill Wave', 'fas fa-money-bill-wave', 'f53a', 'solid'),
(590, 'Money Bill Wave Alt', 'fas fa-money-bill-wave-alt', 'f53b', 'solid'),
(591, 'Money Check', 'fas fa-money-check', 'f53c', 'solid'),
(592, 'Money Check Alt', 'fas fa-money-check-alt', 'f53d', 'solid'),
(593, 'Monument', 'fas fa-monument', 'f5a6', 'solid'),
(594, 'Moon', 'fas fa-moon', 'f186', 'solid'),
(595, 'Mortar Pestle', 'fas fa-mortar-pestle', 'f5a7', 'solid'),
(596, 'Mosque', 'fas fa-mosque', 'f678', 'solid'),
(597, 'Motorcycle', 'fas fa-motorcycle', 'f21c', 'solid'),
(598, 'Mountain', 'fas fa-mountain', 'f6fc', 'solid'),
(599, 'Mouse', 'fas fa-mouse', 'f8cc', 'solid'),
(600, 'Mouse Pointer', 'fas fa-mouse-pointer', 'f245', 'solid'),
(601, 'Mug Hot', 'fas fa-mug-hot', 'f7b6', 'solid'),
(602, 'Music', 'fas fa-music', 'f001', 'solid'),
(603, 'Network Wired', 'fas fa-network-wired', 'f6ff', 'solid'),
(604, 'Neuter', 'fas fa-neuter', 'f22c', 'solid'),
(605, 'Newspaper', 'fas fa-newspaper', 'f1ea', 'solid'),
(606, 'Not Equal', 'fas fa-not-equal', 'f53e', 'solid'),
(607, 'Notes Medical', 'fas fa-notes-medical', 'f481', 'solid'),
(608, 'Object Group', 'fas fa-object-group', 'f247', 'solid'),
(609, 'Object Ungroup', 'fas fa-object-ungroup', 'f248', 'solid'),
(610, 'Oil Can', 'fas fa-oil-can', 'f613', 'solid'),
(611, 'Om', 'fas fa-om', 'f679', 'solid'),
(612, 'Otter', 'fas fa-otter', 'f700', 'solid'),
(613, 'Outdent', 'fas fa-outdent', 'f03b', 'solid'),
(614, 'Pager', 'fas fa-pager', 'f815', 'solid'),
(615, 'Paint Brush', 'fas fa-paint-brush', 'f1fc', 'solid'),
(616, 'Paint Roller', 'fas fa-paint-roller', 'f5aa', 'solid'),
(617, 'Palette', 'fas fa-palette', 'f53f', 'solid'),
(618, 'Pallet', 'fas fa-pallet', 'f482', 'solid'),
(619, 'Paper Plane', 'fas fa-paper-plane', 'f1d8', 'solid'),
(620, 'Paperclip', 'fas fa-paperclip', 'f0c6', 'solid'),
(621, 'Parachute Box', 'fas fa-parachute-box', 'f4cd', 'solid'),
(622, 'Paragraph', 'fas fa-paragraph', 'f1dd', 'solid'),
(623, 'Parking', 'fas fa-parking', 'f540', 'solid'),
(624, 'Passport', 'fas fa-passport', 'f5ab', 'solid'),
(625, 'Pastafarianism', 'fas fa-pastafarianism', 'f67b', 'solid'),
(626, 'Paste', 'fas fa-paste', 'f0ea', 'solid'),
(627, 'Pause', 'fas fa-pause', 'f04c', 'solid'),
(628, 'Pause Circle', 'fas fa-pause-circle', 'f28b', 'solid'),
(629, 'Paw', 'fas fa-paw', 'f1b0', 'solid'),
(630, 'Peace', 'fas fa-peace', 'f67c', 'solid'),
(631, 'Pen', 'fas fa-pen', 'f304', 'solid'),
(632, 'Pen Alt', 'fas fa-pen-alt', 'f305', 'solid'),
(633, 'Pen Fancy', 'fas fa-pen-fancy', 'f5ac', 'solid'),
(634, 'Pen Nib', 'fas fa-pen-nib', 'f5ad', 'solid'),
(635, 'Pen Square', 'fas fa-pen-square', 'f14b', 'solid'),
(636, 'Pencil Alt', 'fas fa-pencil-alt', 'f303', 'solid'),
(637, 'Pencil Ruler', 'fas fa-pencil-ruler', 'f5ae', 'solid'),
(638, 'People Arrows', 'fas fa-people-arrows', 'e068', 'solid'),
(639, 'People Carry', 'fas fa-people-carry', 'f4ce', 'solid'),
(640, 'Pepper Hot', 'fas fa-pepper-hot', 'f816', 'solid'),
(641, 'Percent', 'fas fa-percent', 'f295', 'solid'),
(642, 'Percentage', 'fas fa-percentage', 'f541', 'solid'),
(643, 'Person Booth', 'fas fa-person-booth', 'f756', 'solid'),
(644, 'Phone', 'fas fa-phone', 'f095', 'solid'),
(645, 'Phone Alt', 'fas fa-phone-alt', 'f879', 'solid'),
(646, 'Phone Slash', 'fas fa-phone-slash', 'f3dd', 'solid'),
(647, 'Phone Square', 'fas fa-phone-square', 'f098', 'solid'),
(648, 'Phone Square Alt', 'fas fa-phone-square-alt', 'f87b', 'solid'),
(649, 'Phone Volume', 'fas fa-phone-volume', 'f2a0', 'solid'),
(650, 'Photo Video', 'fas fa-photo-video', 'f87c', 'solid'),
(651, 'Piggy Bank', 'fas fa-piggy-bank', 'f4d3', 'solid'),
(652, 'Pills', 'fas fa-pills', 'f484', 'solid'),
(653, 'Pizza Slice', 'fas fa-pizza-slice', 'f818', 'solid'),
(654, 'Place Of Worship', 'fas fa-place-of-worship', 'f67f', 'solid'),
(655, 'Plane', 'fas fa-plane', 'f072', 'solid'),
(656, 'Plane Arrival', 'fas fa-plane-arrival', 'f5af', 'solid'),
(657, 'Plane Departure', 'fas fa-plane-departure', 'f5b0', 'solid'),
(658, 'Plane Slash', 'fas fa-plane-slash', 'e069', 'solid'),
(659, 'Play', 'fas fa-play', 'f04b', 'solid'),
(660, 'Play Circle', 'fas fa-play-circle', 'f144', 'solid'),
(661, 'Plug', 'fas fa-plug', 'f1e6', 'solid'),
(662, 'Plus', 'fas fa-plus', 'f067', 'solid'),
(663, 'Plus Circle', 'fas fa-plus-circle', 'f055', 'solid'),
(664, 'Plus Square', 'fas fa-plus-square', 'f0fe', 'solid'),
(665, 'Podcast', 'fas fa-podcast', 'f2ce', 'solid'),
(666, 'Poll', 'fas fa-poll', 'f681', 'solid'),
(667, 'Poll H', 'fas fa-poll-h', 'f682', 'solid'),
(668, 'Poo', 'fas fa-poo', 'f2fe', 'solid'),
(669, 'Poo Storm', 'fas fa-poo-storm', 'f75a', 'solid'),
(670, 'Poop', 'fas fa-poop', 'f619', 'solid'),
(671, 'Portrait', 'fas fa-portrait', 'f3e0', 'solid'),
(672, 'Pound Sign', 'fas fa-pound-sign', 'f154', 'solid'),
(673, 'Power Off', 'fas fa-power-off', 'f011', 'solid'),
(674, 'Pray', 'fas fa-pray', 'f683', 'solid'),
(675, 'Praying Hands', 'fas fa-praying-hands', 'f684', 'solid'),
(676, 'Prescription', 'fas fa-prescription', 'f5b1', 'solid'),
(677, 'Prescription Bottle', 'fas fa-prescription-bottle', 'f485', 'solid'),
(678, 'Prescription Bottle Alt', 'fas fa-prescription-bottle-alt', 'f486', 'solid'),
(679, 'Print', 'fas fa-print', 'f02f', 'solid'),
(680, 'Procedures', 'fas fa-procedures', 'f487', 'solid'),
(681, 'Project Diagram', 'fas fa-project-diagram', 'f542', 'solid'),
(682, 'Pump Medical', 'fas fa-pump-medical', 'e06a', 'solid'),
(683, 'Pump Soap', 'fas fa-pump-soap', 'e06b', 'solid'),
(684, 'Puzzle Piece', 'fas fa-puzzle-piece', 'f12e', 'solid'),
(685, 'Qrcode', 'fas fa-qrcode', 'f029', 'solid'),
(686, 'Question', 'fas fa-question', 'f128', 'solid'),
(687, 'Question Circle', 'fas fa-question-circle', 'f059', 'solid'),
(688, 'Quidditch', 'fas fa-quidditch', 'f458', 'solid'),
(689, 'Quote Left', 'fas fa-quote-left', 'f10d', 'solid'),
(690, 'Quote Right', 'fas fa-quote-right', 'f10e', 'solid'),
(691, 'Quran', 'fas fa-quran', 'f687', 'solid'),
(692, 'Radiation', 'fas fa-radiation', 'f7b9', 'solid'),
(693, 'Radiation Alt', 'fas fa-radiation-alt', 'f7ba', 'solid'),
(694, 'Rainbow', 'fas fa-rainbow', 'f75b', 'solid'),
(695, 'Random', 'fas fa-random', 'f074', 'solid'),
(696, 'Receipt', 'fas fa-receipt', 'f543', 'solid'),
(697, 'Record Vinyl', 'fas fa-record-vinyl', 'f8d9', 'solid'),
(698, 'Recycle', 'fas fa-recycle', 'f1b8', 'solid'),
(699, 'Redo', 'fas fa-redo', 'f01e', 'solid'),
(700, 'Redo Alt', 'fas fa-redo-alt', 'f2f9', 'solid'),
(701, 'Registered', 'fas fa-registered', 'f25d', 'solid'),
(702, 'Remove Format', 'fas fa-remove-format', 'f87d', 'solid'),
(703, 'Reply', 'fas fa-reply', 'f3e5', 'solid'),
(704, 'Reply All', 'fas fa-reply-all', 'f122', 'solid'),
(705, 'Republican', 'fas fa-republican', 'f75e', 'solid'),
(706, 'Restroom', 'fas fa-restroom', 'f7bd', 'solid'),
(707, 'Retweet', 'fas fa-retweet', 'f079', 'solid'),
(708, 'Ribbon', 'fas fa-ribbon', 'f4d6', 'solid'),
(709, 'Ring', 'fas fa-ring', 'f70b', 'solid'),
(710, 'Road', 'fas fa-road', 'f018', 'solid'),
(711, 'Robot', 'fas fa-robot', 'f544', 'solid'),
(712, 'Rocket', 'fas fa-rocket', 'f135', 'solid'),
(713, 'Route', 'fas fa-route', 'f4d7', 'solid'),
(714, 'Rss', 'fas fa-rss', 'f09e', 'solid'),
(715, 'Rss Square', 'fas fa-rss-square', 'f143', 'solid'),
(716, 'Ruble Sign', 'fas fa-ruble-sign', 'f158', 'solid'),
(717, 'Ruler', 'fas fa-ruler', 'f545', 'solid'),
(718, 'Ruler Combined', 'fas fa-ruler-combined', 'f546', 'solid'),
(719, 'Ruler Horizontal', 'fas fa-ruler-horizontal', 'f547', 'solid'),
(720, 'Ruler Vertical', 'fas fa-ruler-vertical', 'f548', 'solid'),
(721, 'Running', 'fas fa-running', 'f70c', 'solid'),
(722, 'Rupee Sign', 'fas fa-rupee-sign', 'f156', 'solid'),
(723, 'Sad Cry', 'fas fa-sad-cry', 'f5b3', 'solid'),
(724, 'Sad Tear', 'fas fa-sad-tear', 'f5b4', 'solid'),
(725, 'Satellite', 'fas fa-satellite', 'f7bf', 'solid'),
(726, 'Satellite Dish', 'fas fa-satellite-dish', 'f7c0', 'solid'),
(727, 'Save', 'fas fa-save', 'f0c7', 'solid'),
(728, 'School', 'fas fa-school', 'f549', 'solid'),
(729, 'Screwdriver', 'fas fa-screwdriver', 'f54a', 'solid'),
(730, 'Scroll', 'fas fa-scroll', 'f70e', 'solid'),
(731, 'Sd Card', 'fas fa-sd-card', 'f7c2', 'solid'),
(732, 'Search', 'fas fa-search', 'f002', 'solid'),
(733, 'Search Dollar', 'fas fa-search-dollar', 'f688', 'solid'),
(734, 'Search Location', 'fas fa-search-location', 'f689', 'solid'),
(735, 'Search Minus', 'fas fa-search-minus', 'f010', 'solid'),
(736, 'Search Plus', 'fas fa-search-plus', 'f00e', 'solid'),
(737, 'Seedling', 'fas fa-seedling', 'f4d8', 'solid'),
(738, 'Server', 'fas fa-server', 'f233', 'solid'),
(739, 'Shapes', 'fas fa-shapes', 'f61f', 'solid'),
(740, 'Share', 'fas fa-share', 'f064', 'solid'),
(741, 'Share Alt', 'fas fa-share-alt', 'f1e0', 'solid'),
(742, 'Share Alt Square', 'fas fa-share-alt-square', 'f1e1', 'solid'),
(743, 'Share Square', 'fas fa-share-square', 'f14d', 'solid'),
(744, 'Shekel Sign', 'fas fa-shekel-sign', 'f20b', 'solid'),
(745, 'Shield Alt', 'fas fa-shield-alt', 'f3ed', 'solid'),
(746, 'Shield Virus', 'fas fa-shield-virus', 'e06c', 'solid'),
(747, 'Ship', 'fas fa-ship', 'f21a', 'solid'),
(748, 'Shipping Fast', 'fas fa-shipping-fast', 'f48b', 'solid'),
(749, 'Shoe Prints', 'fas fa-shoe-prints', 'f54b', 'solid'),
(750, 'Shopping Bag', 'fas fa-shopping-bag', 'f290', 'solid'),
(751, 'Shopping Basket', 'fas fa-shopping-basket', 'f291', 'solid'),
(752, 'Shopping Cart', 'fas fa-shopping-cart', 'f07a', 'solid'),
(753, 'Shower', 'fas fa-shower', 'f2cc', 'solid'),
(754, 'Shuttle Van', 'fas fa-shuttle-van', 'f5b6', 'solid'),
(755, 'Sign', 'fas fa-sign', 'f4d9', 'solid'),
(756, 'Sign In Alt', 'fas fa-sign-in-alt', 'f2f6', 'solid'),
(757, 'Sign Language', 'fas fa-sign-language', 'f2a7', 'solid'),
(758, 'Sign Out Alt', 'fas fa-sign-out-alt', 'f2f5', 'solid'),
(759, 'Signal', 'fas fa-signal', 'f012', 'solid'),
(760, 'Signature', 'fas fa-signature', 'f5b7', 'solid'),
(761, 'Sim Card', 'fas fa-sim-card', 'f7c4', 'solid'),
(762, 'Sink', 'fas fa-sink', 'e06d', 'solid'),
(763, 'Sitemap', 'fas fa-sitemap', 'f0e8', 'solid'),
(764, 'Skating', 'fas fa-skating', 'f7c5', 'solid'),
(765, 'Skiing', 'fas fa-skiing', 'f7c9', 'solid'),
(766, 'Skiing Nordic', 'fas fa-skiing-nordic', 'f7ca', 'solid'),
(767, 'Skull', 'fas fa-skull', 'f54c', 'solid'),
(768, 'Skull Crossbones', 'fas fa-skull-crossbones', 'f714', 'solid'),
(769, 'Slash', 'fas fa-slash', 'f715', 'solid'),
(770, 'Sleigh', 'fas fa-sleigh', 'f7cc', 'solid'),
(771, 'Sliders H', 'fas fa-sliders-h', 'f1de', 'solid'),
(772, 'Smile', 'fas fa-smile', 'f118', 'solid'),
(773, 'Smile Beam', 'fas fa-smile-beam', 'f5b8', 'solid'),
(774, 'Smile Wink', 'fas fa-smile-wink', 'f4da', 'solid'),
(775, 'Smog', 'fas fa-smog', 'f75f', 'solid'),
(776, 'Smoking', 'fas fa-smoking', 'f48d', 'solid'),
(777, 'Smoking Ban', 'fas fa-smoking-ban', 'f54d', 'solid'),
(778, 'Sms', 'fas fa-sms', 'f7cd', 'solid'),
(779, 'Snowboarding', 'fas fa-snowboarding', 'f7ce', 'solid'),
(780, 'Snowflake', 'fas fa-snowflake', 'f2dc', 'solid'),
(781, 'Snowman', 'fas fa-snowman', 'f7d0', 'solid'),
(782, 'Snowplow', 'fas fa-snowplow', 'f7d2', 'solid'),
(783, 'Soap', 'fas fa-soap', 'e06e', 'solid'),
(784, 'Socks', 'fas fa-socks', 'f696', 'solid'),
(785, 'Solar Panel', 'fas fa-solar-panel', 'f5ba', 'solid'),
(786, 'Sort', 'fas fa-sort', 'f0dc', 'solid'),
(787, 'Sort Alpha Down', 'fas fa-sort-alpha-down', 'f15d', 'solid'),
(788, 'Sort Alpha Down Alt', 'fas fa-sort-alpha-down-alt', 'f881', 'solid'),
(789, 'Sort Alpha Up', 'fas fa-sort-alpha-up', 'f15e', 'solid'),
(790, 'Sort Alpha Up Alt', 'fas fa-sort-alpha-up-alt', 'f882', 'solid'),
(791, 'Sort Amount Down', 'fas fa-sort-amount-down', 'f160', 'solid'),
(792, 'Sort Amount Down Alt', 'fas fa-sort-amount-down-alt', 'f884', 'solid'),
(793, 'Sort Amount Up', 'fas fa-sort-amount-up', 'f161', 'solid'),
(794, 'Sort Amount Up Alt', 'fas fa-sort-amount-up-alt', 'f885', 'solid'),
(795, 'Sort Down', 'fas fa-sort-down', 'f0dd', 'solid'),
(796, 'Sort Numeric Down', 'fas fa-sort-numeric-down', 'f162', 'solid'),
(797, 'Sort Numeric Down Alt', 'fas fa-sort-numeric-down-alt', 'f886', 'solid'),
(798, 'Sort Numeric Up', 'fas fa-sort-numeric-up', 'f163', 'solid'),
(799, 'Sort Numeric Up Alt', 'fas fa-sort-numeric-up-alt', 'f887', 'solid'),
(800, 'Sort Up', 'fas fa-sort-up', 'f0de', 'solid'),
(801, 'Spa', 'fas fa-spa', 'f5bb', 'solid'),
(802, 'Space Shuttle', 'fas fa-space-shuttle', 'f197', 'solid'),
(803, 'Spell Check', 'fas fa-spell-check', 'f891', 'solid'),
(804, 'Spider', 'fas fa-spider', 'f717', 'solid'),
(805, 'Spinner', 'fas fa-spinner', 'f110', 'solid'),
(806, 'Splotch', 'fas fa-splotch', 'f5bc', 'solid'),
(807, 'Spray Can', 'fas fa-spray-can', 'f5bd', 'solid'),
(808, 'Square', 'fas fa-square', 'f0c8', 'solid'),
(809, 'Square Full', 'fas fa-square-full', 'f45c', 'solid'),
(810, 'Square Root Alt', 'fas fa-square-root-alt', 'f698', 'solid'),
(811, 'Stamp', 'fas fa-stamp', 'f5bf', 'solid'),
(812, 'Star', 'fas fa-star', 'f005', 'solid'),
(813, 'Star And Crescent', 'fas fa-star-and-crescent', 'f699', 'solid'),
(814, 'Star Half', 'fas fa-star-half', 'f089', 'solid'),
(815, 'Star Half Alt', 'fas fa-star-half-alt', 'f5c0', 'solid'),
(816, 'Star Of David', 'fas fa-star-of-david', 'f69a', 'solid'),
(817, 'Star Of Life', 'fas fa-star-of-life', 'f621', 'solid'),
(818, 'Step Backward', 'fas fa-step-backward', 'f048', 'solid'),
(819, 'Step Forward', 'fas fa-step-forward', 'f051', 'solid'),
(820, 'Stethoscope', 'fas fa-stethoscope', 'f0f1', 'solid'),
(821, 'Sticky Note', 'fas fa-sticky-note', 'f249', 'solid'),
(822, 'Stop', 'fas fa-stop', 'f04d', 'solid'),
(823, 'Stop Circle', 'fas fa-stop-circle', 'f28d', 'solid'),
(824, 'Stopwatch', 'fas fa-stopwatch', 'f2f2', 'solid'),
(825, 'Stopwatch 20', 'fas fa-stopwatch-20', 'e06f', 'solid'),
(826, 'Store', 'fas fa-store', 'f54e', 'solid'),
(827, 'Store Alt', 'fas fa-store-alt', 'f54f', 'solid'),
(828, 'Store Alt Slash', 'fas fa-store-alt-slash', 'e070', 'solid'),
(829, 'Store Slash', 'fas fa-store-slash', 'e071', 'solid'),
(830, 'Stream', 'fas fa-stream', 'f550', 'solid'),
(831, 'Street View', 'fas fa-street-view', 'f21d', 'solid'),
(832, 'Strikethrough', 'fas fa-strikethrough', 'f0cc', 'solid'),
(833, 'Stroopwafel', 'fas fa-stroopwafel', 'f551', 'solid'),
(834, 'Subscript', 'fas fa-subscript', 'f12c', 'solid'),
(835, 'Subway', 'fas fa-subway', 'f239', 'solid'),
(836, 'Suitcase', 'fas fa-suitcase', 'f0f2', 'solid'),
(837, 'Suitcase Rolling', 'fas fa-suitcase-rolling', 'f5c1', 'solid'),
(838, 'Sun', 'fas fa-sun', 'f185', 'solid'),
(839, 'Superscript', 'fas fa-superscript', 'f12b', 'solid'),
(840, 'Surprise', 'fas fa-surprise', 'f5c2', 'solid'),
(841, 'Swatchbook', 'fas fa-swatchbook', 'f5c3', 'solid'),
(842, 'Swimmer', 'fas fa-swimmer', 'f5c4', 'solid'),
(843, 'Swimming Pool', 'fas fa-swimming-pool', 'f5c5', 'solid'),
(844, 'Synagogue', 'fas fa-synagogue', 'f69b', 'solid'),
(845, 'Sync', 'fas fa-sync', 'f021', 'solid'),
(846, 'Sync Alt', 'fas fa-sync-alt', 'f2f1', 'solid'),
(847, 'Syringe', 'fas fa-syringe', 'f48e', 'solid'),
(848, 'Table', 'fas fa-table', 'f0ce', 'solid'),
(849, 'Table Tennis', 'fas fa-table-tennis', 'f45d', 'solid'),
(850, 'Tablet', 'fas fa-tablet', 'f10a', 'solid'),
(851, 'Tablet Alt', 'fas fa-tablet-alt', 'f3fa', 'solid'),
(852, 'Tablets', 'fas fa-tablets', 'f490', 'solid'),
(853, 'Tachometer Alt', 'fas fa-tachometer-alt', 'f3fd', 'solid'),
(854, 'Tag', 'fas fa-tag', 'f02b', 'solid'),
(855, 'Tags', 'fas fa-tags', 'f02c', 'solid'),
(856, 'Tape', 'fas fa-tape', 'f4db', 'solid'),
(857, 'Tasks', 'fas fa-tasks', 'f0ae', 'solid'),
(858, 'Taxi', 'fas fa-taxi', 'f1ba', 'solid'),
(859, 'Teeth', 'fas fa-teeth', 'f62e', 'solid'),
(860, 'Teeth Open', 'fas fa-teeth-open', 'f62f', 'solid'),
(861, 'Temperature High', 'fas fa-temperature-high', 'f769', 'solid'),
(862, 'Temperature Low', 'fas fa-temperature-low', 'f76b', 'solid'),
(863, 'Tenge', 'fas fa-tenge', 'f7d7', 'solid'),
(864, 'Terminal', 'fas fa-terminal', 'f120', 'solid'),
(865, 'Text Height', 'fas fa-text-height', 'f034', 'solid'),
(866, 'Text Width', 'fas fa-text-width', 'f035', 'solid'),
(867, 'Th', 'fas fa-th', 'f00a', 'solid'),
(868, 'Th Large', 'fas fa-th-large', 'f009', 'solid'),
(869, 'Th List', 'fas fa-th-list', 'f00b', 'solid'),
(870, 'Theater Masks', 'fas fa-theater-masks', 'f630', 'solid'),
(871, 'Thermometer', 'fas fa-thermometer', 'f491', 'solid'),
(872, 'Thermometer Empty', 'fas fa-thermometer-empty', 'f2cb', 'solid'),
(873, 'Thermometer Full', 'fas fa-thermometer-full', 'f2c7', 'solid'),
(874, 'Thermometer Half', 'fas fa-thermometer-half', 'f2c9', 'solid'),
(875, 'Thermometer Quarter', 'fas fa-thermometer-quarter', 'f2ca', 'solid'),
(876, 'Thermometer Three Quarters', 'fas fa-thermometer-three-quarters', 'f2c8', 'solid'),
(877, 'Thumbs Down', 'fas fa-thumbs-down', 'f165', 'solid'),
(878, 'Thumbs Up', 'fas fa-thumbs-up', 'f164', 'solid'),
(879, 'Thumbtack', 'fas fa-thumbtack', 'f08d', 'solid'),
(880, 'Ticket Alt', 'fas fa-ticket-alt', 'f3ff', 'solid'),
(881, 'Times', 'fas fa-times', 'f00d', 'solid'),
(882, 'Times Circle', 'fas fa-times-circle', 'f057', 'solid'),
(883, 'Tint', 'fas fa-tint', 'f043', 'solid'),
(884, 'Tint Slash', 'fas fa-tint-slash', 'f5c7', 'solid'),
(885, 'Tired', 'fas fa-tired', 'f5c8', 'solid'),
(886, 'Toggle Off', 'fas fa-toggle-off', 'f204', 'solid');

INSERT INTO `_fa5` (`id`, `nama`, `class`, `unicode`, `kategori`) VALUES
(887, 'Toggle On', 'fas fa-toggle-on', 'f205', 'solid'),
(888, 'Toilet', 'fas fa-toilet', 'f7d8', 'solid'),
(889, 'Toilet Paper', 'fas fa-toilet-paper', 'f71e', 'solid'),
(890, 'Toilet Paper Slash', 'fas fa-toilet-paper-slash', 'e072', 'solid'),
(891, 'Toolbox', 'fas fa-toolbox', 'f552', 'solid'),
(892, 'Tools', 'fas fa-tools', 'f7d9', 'solid'),
(893, 'Tooth', 'fas fa-tooth', 'f5c9', 'solid'),
(894, 'Torah', 'fas fa-torah', 'f6a0', 'solid'),
(895, 'Torii Gate', 'fas fa-torii-gate', 'f6a1', 'solid'),
(896, 'Tractor', 'fas fa-tractor', 'f722', 'solid'),
(897, 'Trademark', 'fas fa-trademark', 'f25c', 'solid'),
(898, 'Traffic Light', 'fas fa-traffic-light', 'f637', 'solid'),
(899, 'Trailer', 'fas fa-trailer', 'e041', 'solid'),
(900, 'Train', 'fas fa-train', 'f238', 'solid'),
(901, 'Tram', 'fas fa-tram', 'f7da', 'solid'),
(902, 'Transgender', 'fas fa-transgender', 'f224', 'solid'),
(903, 'Transgender Alt', 'fas fa-transgender-alt', 'f225', 'solid'),
(904, 'Trash', 'fas fa-trash', 'f1f8', 'solid'),
(905, 'Trash Alt', 'fas fa-trash-alt', 'f2ed', 'solid'),
(906, 'Trash Restore', 'fas fa-trash-restore', 'f829', 'solid'),
(907, 'Trash Restore Alt', 'fas fa-trash-restore-alt', 'f82a', 'solid'),
(908, 'Tree', 'fas fa-tree', 'f1bb', 'solid'),
(909, 'Trophy', 'fas fa-trophy', 'f091', 'solid'),
(910, 'Truck', 'fas fa-truck', 'f0d1', 'solid'),
(911, 'Truck Loading', 'fas fa-truck-loading', 'f4de', 'solid'),
(912, 'Truck Monster', 'fas fa-truck-monster', 'f63b', 'solid'),
(913, 'Truck Moving', 'fas fa-truck-moving', 'f4df', 'solid'),
(914, 'Truck Pickup', 'fas fa-truck-pickup', 'f63c', 'solid'),
(915, 'Tshirt', 'fas fa-tshirt', 'f553', 'solid'),
(916, 'Tty', 'fas fa-tty', 'f1e4', 'solid'),
(917, 'Tv', 'fas fa-tv', 'f26c', 'solid'),
(918, 'Umbrella', 'fas fa-umbrella', 'f0e9', 'solid'),
(919, 'Umbrella Beach', 'fas fa-umbrella-beach', 'f5ca', 'solid'),
(920, 'Underline', 'fas fa-underline', 'f0cd', 'solid'),
(921, 'Undo', 'fas fa-undo', 'f0e2', 'solid'),
(922, 'Undo Alt', 'fas fa-undo-alt', 'f2ea', 'solid'),
(923, 'Universal Access', 'fas fa-universal-access', 'f29a', 'solid'),
(924, 'University', 'fas fa-university', 'f19c', 'solid'),
(925, 'Unlink', 'fas fa-unlink', 'f127', 'solid'),
(926, 'Unlock', 'fas fa-unlock', 'f09c', 'solid'),
(927, 'Unlock Alt', 'fas fa-unlock-alt', 'f13e', 'solid'),
(928, 'Upload', 'fas fa-upload', 'f093', 'solid'),
(929, 'User', 'fas fa-user', 'f007', 'solid'),
(930, 'User Alt', 'fas fa-user-alt', 'f406', 'solid'),
(931, 'User Alt Slash', 'fas fa-user-alt-slash', 'f4fa', 'solid'),
(932, 'User Astronaut', 'fas fa-user-astronaut', 'f4fb', 'solid'),
(933, 'User Check', 'fas fa-user-check', 'f4fc', 'solid'),
(934, 'User Circle', 'fas fa-user-circle', 'f2bd', 'solid'),
(935, 'User Clock', 'fas fa-user-clock', 'f4fd', 'solid'),
(936, 'User Cog', 'fas fa-user-cog', 'f4fe', 'solid'),
(937, 'User Edit', 'fas fa-user-edit', 'f4ff', 'solid'),
(938, 'User Friends', 'fas fa-user-friends', 'f500', 'solid'),
(939, 'User Graduate', 'fas fa-user-graduate', 'f501', 'solid'),
(940, 'User Injured', 'fas fa-user-injured', 'f728', 'solid'),
(941, 'User Lock', 'fas fa-user-lock', 'f502', 'solid'),
(942, 'User Md', 'fas fa-user-md', 'f0f0', 'solid'),
(943, 'User Minus', 'fas fa-user-minus', 'f503', 'solid'),
(944, 'User Ninja', 'fas fa-user-ninja', 'f504', 'solid'),
(945, 'User Nurse', 'fas fa-user-nurse', 'f82f', 'solid'),
(946, 'User Plus', 'fas fa-user-plus', 'f234', 'solid'),
(947, 'User Secret', 'fas fa-user-secret', 'f21b', 'solid'),
(948, 'User Shield', 'fas fa-user-shield', 'f505', 'solid'),
(949, 'User Slash', 'fas fa-user-slash', 'f506', 'solid'),
(950, 'User Tag', 'fas fa-user-tag', 'f507', 'solid'),
(951, 'User Tie', 'fas fa-user-tie', 'f508', 'solid'),
(952, 'User Times', 'fas fa-user-times', 'f235', 'solid'),
(953, 'Users', 'fas fa-users', 'f0c0', 'solid'),
(954, 'Users Cog', 'fas fa-users-cog', 'f509', 'solid'),
(955, 'Users Slash', 'fas fa-users-slash', 'e073', 'solid'),
(956, 'Utensil Spoon', 'fas fa-utensil-spoon', 'f2e5', 'solid'),
(957, 'Utensils', 'fas fa-utensils', 'f2e7', 'solid'),
(958, 'Vector Square', 'fas fa-vector-square', 'f5cb', 'solid'),
(959, 'Venus', 'fas fa-venus', 'f221', 'solid'),
(960, 'Venus Double', 'fas fa-venus-double', 'f226', 'solid'),
(961, 'Venus Mars', 'fas fa-venus-mars', 'f228', 'solid'),
(962, 'Vest', 'fas fa-vest', 'e085', 'solid'),
(963, 'Vest Patches', 'fas fa-vest-patches', 'e086', 'solid'),
(964, 'Vial', 'fas fa-vial', 'f492', 'solid'),
(965, 'Vials', 'fas fa-vials', 'f493', 'solid'),
(966, 'Video', 'fas fa-video', 'f03d', 'solid'),
(967, 'Video Slash', 'fas fa-video-slash', 'f4e2', 'solid'),
(968, 'Vihara', 'fas fa-vihara', 'f6a7', 'solid'),
(969, 'Virus', 'fas fa-virus', 'e074', 'solid'),
(970, 'Virus Slash', 'fas fa-virus-slash', 'e075', 'solid'),
(971, 'Viruses', 'fas fa-viruses', 'e076', 'solid'),
(972, 'Voicemail', 'fas fa-voicemail', 'f897', 'solid'),
(973, 'Volleyball Ball', 'fas fa-volleyball-ball', 'f45f', 'solid'),
(974, 'Volume Down', 'fas fa-volume-down', 'f027', 'solid'),
(975, 'Volume Mute', 'fas fa-volume-mute', 'f6a9', 'solid'),
(976, 'Volume Off', 'fas fa-volume-off', 'f026', 'solid'),
(977, 'Volume Up', 'fas fa-volume-up', 'f028', 'solid'),
(978, 'Vote Yea', 'fas fa-vote-yea', 'f772', 'solid'),
(979, 'Vr Cardboard', 'fas fa-vr-cardboard', 'f729', 'solid'),
(980, 'Walking', 'fas fa-walking', 'f554', 'solid'),
(981, 'Wallet', 'fas fa-wallet', 'f555', 'solid'),
(982, 'Warehouse', 'fas fa-warehouse', 'f494', 'solid'),
(983, 'Water', 'fas fa-water', 'f773', 'solid'),
(984, 'Wave Square', 'fas fa-wave-square', 'f83e', 'solid'),
(985, 'Weight', 'fas fa-weight', 'f496', 'solid'),
(986, 'Weight Hanging', 'fas fa-weight-hanging', 'f5cd', 'solid'),
(987, 'Wheelchair', 'fas fa-wheelchair', 'f193', 'solid'),
(988, 'Wifi', 'fas fa-wifi', 'f1eb', 'solid'),
(989, 'Wind', 'fas fa-wind', 'f72e', 'solid'),
(990, 'Window Close', 'fas fa-window-close', 'f410', 'solid'),
(991, 'Window Maximize', 'fas fa-window-maximize', 'f2d0', 'solid'),
(992, 'Window Minimize', 'fas fa-window-minimize', 'f2d1', 'solid'),
(993, 'Window Restore', 'fas fa-window-restore', 'f2d2', 'solid'),
(994, 'Wine Bottle', 'fas fa-wine-bottle', 'f72f', 'solid'),
(995, 'Wine Glass', 'fas fa-wine-glass', 'f4e3', 'solid'),
(996, 'Wine Glass Alt', 'fas fa-wine-glass-alt', 'f5ce', 'solid'),
(997, 'Won Sign', 'fas fa-won-sign', 'f159', 'solid'),
(998, 'Wrench', 'fas fa-wrench', 'f0ad', 'solid'),
(999, 'X Ray', 'fas fa-x-ray', 'f497', 'solid'),
(1000, 'Yen Sign', 'fas fa-yen-sign', 'f157', 'solid'),
(1001, 'Yin Yang', 'fas fa-yin-yang', 'f6ad', 'solid'),
(1002, '500Px', 'fab fa-500px', 'f26e', 'brands'),
(1003, 'Accessible Icon', 'fab fa-accessible-icon', 'f368', 'brands'),
(1004, 'Accusoft', 'fab fa-accusoft', 'f369', 'brands'),
(1005, 'Acquisitions Incorporated', 'fab fa-acquisitions-incorporated', 'f6af', 'brands'),
(1006, 'Adn', 'fab fa-adn', 'f170', 'brands'),
(1007, 'Adversal', 'fab fa-adversal', 'f36a', 'brands'),
(1008, 'Affiliatetheme', 'fab fa-affiliatetheme', 'f36b', 'brands'),
(1009, 'Airbnb', 'fab fa-airbnb', 'f834', 'brands'),
(1010, 'Algolia', 'fab fa-algolia', 'f36c', 'brands'),
(1011, 'Alipay', 'fab fa-alipay', 'f642', 'brands'),
(1012, 'Amazon', 'fab fa-amazon', 'f270', 'brands'),
(1013, 'Amazon Pay', 'fab fa-amazon-pay', 'f42c', 'brands'),
(1014, 'Amilia', 'fab fa-amilia', 'f36d', 'brands'),
(1015, 'Android', 'fab fa-android', 'f17b', 'brands'),
(1016, 'Angellist', 'fab fa-angellist', 'f209', 'brands'),
(1017, 'Angrycreative', 'fab fa-angrycreative', 'f36e', 'brands'),
(1018, 'Angular', 'fab fa-angular', 'f420', 'brands'),
(1019, 'App Store', 'fab fa-app-store', 'f36f', 'brands'),
(1020, 'App Store Ios', 'fab fa-app-store-ios', 'f370', 'brands'),
(1021, 'Apper', 'fab fa-apper', 'f371', 'brands'),
(1022, 'Apple', 'fab fa-apple', 'f179', 'brands'),
(1023, 'Apple Pay', 'fab fa-apple-pay', 'f415', 'brands'),
(1024, 'Artstation', 'fab fa-artstation', 'f77a', 'brands'),
(1025, 'Asymmetrik', 'fab fa-asymmetrik', 'f372', 'brands'),
(1026, 'Atlassian', 'fab fa-atlassian', 'f77b', 'brands'),
(1027, 'Audible', 'fab fa-audible', 'f373', 'brands'),
(1028, 'Autoprefixer', 'fab fa-autoprefixer', 'f41c', 'brands'),
(1029, 'Avianex', 'fab fa-avianex', 'f374', 'brands'),
(1030, 'Aviato', 'fab fa-aviato', 'f421', 'brands'),
(1031, 'Aws', 'fab fa-aws', 'f375', 'brands'),
(1032, 'Bandcamp', 'fab fa-bandcamp', 'f2d5', 'brands'),
(1033, 'Battle Net', 'fab fa-battle-net', 'f835', 'brands'),
(1034, 'Behance', 'fab fa-behance', 'f1b4', 'brands'),
(1035, 'Behance Square', 'fab fa-behance-square', 'f1b5', 'brands'),
(1036, 'Bimobject', 'fab fa-bimobject', 'f378', 'brands'),
(1037, 'Bitbucket', 'fab fa-bitbucket', 'f171', 'brands'),
(1038, 'Bitcoin', 'fab fa-bitcoin', 'f379', 'brands'),
(1039, 'Bity', 'fab fa-bity', 'f37a', 'brands'),
(1040, 'Black Tie', 'fab fa-black-tie', 'f27e', 'brands'),
(1041, 'Blackberry', 'fab fa-blackberry', 'f37b', 'brands'),
(1042, 'Blogger', 'fab fa-blogger', 'f37c', 'brands'),
(1043, 'Blogger B', 'fab fa-blogger-b', 'f37d', 'brands'),
(1044, 'Bluetooth', 'fab fa-bluetooth', 'f293', 'brands'),
(1045, 'Bluetooth B', 'fab fa-bluetooth-b', 'f294', 'brands'),
(1046, 'Bootstrap', 'fab fa-bootstrap', 'f836', 'brands'),
(1047, 'Btc', 'fab fa-btc', 'f15a', 'brands'),
(1048, 'Buffer', 'fab fa-buffer', 'f837', 'brands'),
(1049, 'Buromobelexperte', 'fab fa-buromobelexperte', 'f37f', 'brands'),
(1050, 'Buy N Large', 'fab fa-buy-n-large', 'f8a6', 'brands'),
(1051, 'Buysellads', 'fab fa-buysellads', 'f20d', 'brands'),
(1052, 'Canadian Maple Leaf', 'fab fa-canadian-maple-leaf', 'f785', 'brands'),
(1053, 'Cc Amazon Pay', 'fab fa-cc-amazon-pay', 'f42d', 'brands'),
(1054, 'Cc Amex', 'fab fa-cc-amex', 'f1f3', 'brands'),
(1055, 'Cc Apple Pay', 'fab fa-cc-apple-pay', 'f416', 'brands'),
(1056, 'Cc Diners Club', 'fab fa-cc-diners-club', 'f24c', 'brands'),
(1057, 'Cc Discover', 'fab fa-cc-discover', 'f1f2', 'brands'),
(1058, 'Cc Jcb', 'fab fa-cc-jcb', 'f24b', 'brands'),
(1059, 'Cc Mastercard', 'fab fa-cc-mastercard', 'f1f1', 'brands'),
(1060, 'Cc Paypal', 'fab fa-cc-paypal', 'f1f4', 'brands'),
(1061, 'Cc Stripe', 'fab fa-cc-stripe', 'f1f5', 'brands'),
(1062, 'Cc Visa', 'fab fa-cc-visa', 'f1f0', 'brands'),
(1063, 'Centercode', 'fab fa-centercode', 'f380', 'brands'),
(1064, 'Centos', 'fab fa-centos', 'f789', 'brands'),
(1065, 'Chrome', 'fab fa-chrome', 'f268', 'brands'),
(1066, 'Chromecast', 'fab fa-chromecast', 'f838', 'brands'),
(1067, 'Cloudflare', 'fab fa-cloudflare', 'e07d', 'brands'),
(1068, 'Cloudscale', 'fab fa-cloudscale', 'f383', 'brands'),
(1069, 'Cloudsmith', 'fab fa-cloudsmith', 'f384', 'brands'),
(1070, 'Cloudversify', 'fab fa-cloudversify', 'f385', 'brands'),
(1071, 'Codepen', 'fab fa-codepen', 'f1cb', 'brands'),
(1072, 'Codiepie', 'fab fa-codiepie', 'f284', 'brands'),
(1073, 'Confluence', 'fab fa-confluence', 'f78d', 'brands'),
(1074, 'Connectdevelop', 'fab fa-connectdevelop', 'f20e', 'brands'),
(1075, 'Contao', 'fab fa-contao', 'f26d', 'brands'),
(1076, 'Cotton Bureau', 'fab fa-cotton-bureau', 'f89e', 'brands'),
(1077, 'Cpanel', 'fab fa-cpanel', 'f388', 'brands'),
(1078, 'Creative Commons', 'fab fa-creative-commons', 'f25e', 'brands'),
(1079, 'Creative Commons By', 'fab fa-creative-commons-by', 'f4e7', 'brands'),
(1080, 'Creative Commons Nc', 'fab fa-creative-commons-nc', 'f4e8', 'brands'),
(1081, 'Creative Commons Nc Eu', 'fab fa-creative-commons-nc-eu', 'f4e9', 'brands'),
(1082, 'Creative Commons Nc Jp', 'fab fa-creative-commons-nc-jp', 'f4ea', 'brands'),
(1083, 'Creative Commons Nd', 'fab fa-creative-commons-nd', 'f4eb', 'brands'),
(1084, 'Creative Commons Pd', 'fab fa-creative-commons-pd', 'f4ec', 'brands'),
(1085, 'Creative Commons Pd Alt', 'fab fa-creative-commons-pd-alt', 'f4ed', 'brands'),
(1086, 'Creative Commons Remix', 'fab fa-creative-commons-remix', 'f4ee', 'brands'),
(1087, 'Creative Commons Sa', 'fab fa-creative-commons-sa', 'f4ef', 'brands'),
(1088, 'Creative Commons Sampling', 'fab fa-creative-commons-sampling', 'f4f0', 'brands'),
(1089, 'Creative Commons Sampling Plus', 'fab fa-creative-commons-sampling-plus', 'f4f1', 'brands'),
(1090, 'Creative Commons Share', 'fab fa-creative-commons-share', 'f4f2', 'brands'),
(1091, 'Creative Commons Zero', 'fab fa-creative-commons-zero', 'f4f3', 'brands'),
(1092, 'Critical Role', 'fab fa-critical-role', 'f6c9', 'brands'),
(1093, 'Css3', 'fab fa-css3', 'f13c', 'brands'),
(1094, 'Css3 Alt', 'fab fa-css3-alt', 'f38b', 'brands'),
(1095, 'Cuttlefish', 'fab fa-cuttlefish', 'f38c', 'brands'),
(1096, 'D And D', 'fab fa-d-and-d', 'f38d', 'brands'),
(1097, 'D And D Beyond', 'fab fa-d-and-d-beyond', 'f6ca', 'brands'),
(1098, 'Dailymotion', 'fab fa-dailymotion', 'e052', 'brands'),
(1099, 'Dashcube', 'fab fa-dashcube', 'f210', 'brands'),
(1100, 'Deezer', 'fab fa-deezer', 'e077', 'brands'),
(1101, 'Delicious', 'fab fa-delicious', 'f1a5', 'brands'),
(1102, 'Deploydog', 'fab fa-deploydog', 'f38e', 'brands'),
(1103, 'Deskpro', 'fab fa-deskpro', 'f38f', 'brands'),
(1104, 'Dev', 'fab fa-dev', 'f6cc', 'brands'),
(1105, 'Deviantart', 'fab fa-deviantart', 'f1bd', 'brands'),
(1106, 'Dhl', 'fab fa-dhl', 'f790', 'brands'),
(1107, 'Diaspora', 'fab fa-diaspora', 'f791', 'brands'),
(1108, 'Digg', 'fab fa-digg', 'f1a6', 'brands'),
(1109, 'Digital Ocean', 'fab fa-digital-ocean', 'f391', 'brands'),
(1110, 'Discord', 'fab fa-discord', 'f392', 'brands'),
(1111, 'Discourse', 'fab fa-discourse', 'f393', 'brands'),
(1112, 'Dochub', 'fab fa-dochub', 'f394', 'brands'),
(1113, 'Docker', 'fab fa-docker', 'f395', 'brands'),
(1114, 'Draft2Digital', 'fab fa-draft2digital', 'f396', 'brands'),
(1115, 'Dribbble', 'fab fa-dribbble', 'f17d', 'brands'),
(1116, 'Dribbble Square', 'fab fa-dribbble-square', 'f397', 'brands'),
(1117, 'Dropbox', 'fab fa-dropbox', 'f16b', 'brands'),
(1118, 'Drupal', 'fab fa-drupal', 'f1a9', 'brands'),
(1119, 'Dyalog', 'fab fa-dyalog', 'f399', 'brands'),
(1120, 'Earlybirds', 'fab fa-earlybirds', 'f39a', 'brands'),
(1121, 'Ebay', 'fab fa-ebay', 'f4f4', 'brands'),
(1122, 'Edge', 'fab fa-edge', 'f282', 'brands'),
(1123, 'Edge Legacy', 'fab fa-edge-legacy', 'e078', 'brands'),
(1124, 'Elementor', 'fab fa-elementor', 'f430', 'brands'),
(1125, 'Ello', 'fab fa-ello', 'f5f1', 'brands'),
(1126, 'Ember', 'fab fa-ember', 'f423', 'brands'),
(1127, 'Empire', 'fab fa-empire', 'f1d1', 'brands'),
(1128, 'Envira', 'fab fa-envira', 'f299', 'brands'),
(1129, 'Erlang', 'fab fa-erlang', 'f39d', 'brands'),
(1130, 'Ethereum', 'fab fa-ethereum', 'f42e', 'brands'),
(1131, 'Etsy', 'fab fa-etsy', 'f2d7', 'brands'),
(1132, 'Evernote', 'fab fa-evernote', 'f839', 'brands'),
(1133, 'Expeditedssl', 'fab fa-expeditedssl', 'f23e', 'brands'),
(1134, 'Facebook', 'fab fa-facebook', 'f09a', 'brands'),
(1135, 'Facebook F', 'fab fa-facebook-f', 'f39e', 'brands'),
(1136, 'Facebook Messenger', 'fab fa-facebook-messenger', 'f39f', 'brands'),
(1137, 'Facebook Square', 'fab fa-facebook-square', 'f082', 'brands'),
(1138, 'Fantasy Flight Games', 'fab fa-fantasy-flight-games', 'f6dc', 'brands'),
(1139, 'Fedex', 'fab fa-fedex', 'f797', 'brands'),
(1140, 'Fedora', 'fab fa-fedora', 'f798', 'brands'),
(1141, 'Figma', 'fab fa-figma', 'f799', 'brands'),
(1142, 'Firefox', 'fab fa-firefox', 'f269', 'brands'),
(1143, 'Firefox Browser', 'fab fa-firefox-browser', 'e007', 'brands'),
(1144, 'First Order', 'fab fa-first-order', 'f2b0', 'brands'),
(1145, 'First Order Alt', 'fab fa-first-order-alt', 'f50a', 'brands'),
(1146, 'Firstdraft', 'fab fa-firstdraft', 'f3a1', 'brands'),
(1147, 'Flickr', 'fab fa-flickr', 'f16e', 'brands'),
(1148, 'Flipboard', 'fab fa-flipboard', 'f44d', 'brands'),
(1149, 'Fly', 'fab fa-fly', 'f417', 'brands'),
(1150, 'Font Awesome', 'fab fa-font-awesome', 'f2b4', 'brands'),
(1151, 'Font Awesome Alt', 'fab fa-font-awesome-alt', 'f35c', 'brands'),
(1152, 'Font Awesome Flag', 'fab fa-font-awesome-flag', 'f425', 'brands'),
(1153, 'Fonticons', 'fab fa-fonticons', 'f280', 'brands'),
(1154, 'Fonticons Fi', 'fab fa-fonticons-fi', 'f3a2', 'brands'),
(1155, 'Fort Awesome', 'fab fa-fort-awesome', 'f286', 'brands'),
(1156, 'Fort Awesome Alt', 'fab fa-fort-awesome-alt', 'f3a3', 'brands'),
(1157, 'Forumbee', 'fab fa-forumbee', 'f211', 'brands'),
(1158, 'Foursquare', 'fab fa-foursquare', 'f180', 'brands'),
(1159, 'Free Code Camp', 'fab fa-free-code-camp', 'f2c5', 'brands'),
(1160, 'Freebsd', 'fab fa-freebsd', 'f3a4', 'brands'),
(1161, 'Fulcrum', 'fab fa-fulcrum', 'f50b', 'brands'),
(1162, 'Galactic Republic', 'fab fa-galactic-republic', 'f50c', 'brands'),
(1163, 'Galactic Senate', 'fab fa-galactic-senate', 'f50d', 'brands'),
(1164, 'Get Pocket', 'fab fa-get-pocket', 'f265', 'brands'),
(1165, 'Gg', 'fab fa-gg', 'f260', 'brands'),
(1166, 'Gg Circle', 'fab fa-gg-circle', 'f261', 'brands'),
(1167, 'Git', 'fab fa-git', 'f1d3', 'brands'),
(1168, 'Git Alt', 'fab fa-git-alt', 'f841', 'brands'),
(1169, 'Git Square', 'fab fa-git-square', 'f1d2', 'brands'),
(1170, 'Github', 'fab fa-github', 'f09b', 'brands'),
(1171, 'Github Alt', 'fab fa-github-alt', 'f113', 'brands'),
(1172, 'Github Square', 'fab fa-github-square', 'f092', 'brands'),
(1173, 'Gitkraken', 'fab fa-gitkraken', 'f3a6', 'brands'),
(1174, 'Gitlab', 'fab fa-gitlab', 'f296', 'brands'),
(1175, 'Gitter', 'fab fa-gitter', 'f426', 'brands'),
(1176, 'Glide', 'fab fa-glide', 'f2a5', 'brands'),
(1177, 'Glide G', 'fab fa-glide-g', 'f2a6', 'brands'),
(1178, 'Gofore', 'fab fa-gofore', 'f3a7', 'brands'),
(1179, 'Goodreads', 'fab fa-goodreads', 'f3a8', 'brands'),
(1180, 'Goodreads G', 'fab fa-goodreads-g', 'f3a9', 'brands'),
(1181, 'Google', 'fab fa-google', 'f1a0', 'brands'),
(1182, 'Google Drive', 'fab fa-google-drive', 'f3aa', 'brands'),
(1183, 'Google Pay', 'fab fa-google-pay', 'e079', 'brands'),
(1184, 'Google Play', 'fab fa-google-play', 'f3ab', 'brands'),
(1185, 'Google Plus', 'fab fa-google-plus', 'f2b3', 'brands'),
(1186, 'Google Plus G', 'fab fa-google-plus-g', 'f0d5', 'brands'),
(1187, 'Google Plus Square', 'fab fa-google-plus-square', 'f0d4', 'brands'),
(1188, 'Google Wallet', 'fab fa-google-wallet', 'f1ee', 'brands'),
(1189, 'Gratipay', 'fab fa-gratipay', 'f184', 'brands'),
(1190, 'Grav', 'fab fa-grav', 'f2d6', 'brands'),
(1191, 'Gripfire', 'fab fa-gripfire', 'f3ac', 'brands'),
(1192, 'Grunt', 'fab fa-grunt', 'f3ad', 'brands'),
(1193, 'Guilded', 'fab fa-guilded', 'e07e', 'brands'),
(1194, 'Gulp', 'fab fa-gulp', 'f3ae', 'brands'),
(1195, 'Hacker News', 'fab fa-hacker-news', 'f1d4', 'brands'),
(1196, 'Hacker News Square', 'fab fa-hacker-news-square', 'f3af', 'brands'),
(1197, 'Hackerrank', 'fab fa-hackerrank', 'f5f7', 'brands'),
(1198, 'Hips', 'fab fa-hips', 'f452', 'brands'),
(1199, 'Hire A Helper', 'fab fa-hire-a-helper', 'f3b0', 'brands'),
(1200, 'Hive', 'fab fa-hive', 'e07f', 'brands'),
(1201, 'Hooli', 'fab fa-hooli', 'f427', 'brands'),
(1202, 'Hornbill', 'fab fa-hornbill', 'f592', 'brands'),
(1203, 'Hotjar', 'fab fa-hotjar', 'f3b1', 'brands'),
(1204, 'Houzz', 'fab fa-houzz', 'f27c', 'brands'),
(1205, 'Html5', 'fab fa-html5', 'f13b', 'brands'),
(1206, 'Hubspot', 'fab fa-hubspot', 'f3b2', 'brands'),
(1207, 'Ideal', 'fab fa-ideal', 'e013', 'brands'),
(1208, 'Imdb', 'fab fa-imdb', 'f2d8', 'brands'),
(1209, 'Innosoft', 'fab fa-innosoft', 'e080', 'brands'),
(1210, 'Instagram', 'fab fa-instagram', 'f16d', 'brands'),
(1211, 'Instagram Square', 'fab fa-instagram-square', 'e055', 'brands'),
(1212, 'Instalod', 'fab fa-instalod', 'e081', 'brands'),
(1213, 'Intercom', 'fab fa-intercom', 'f7af', 'brands'),
(1214, 'Internet Explorer', 'fab fa-internet-explorer', 'f26b', 'brands'),
(1215, 'Invision', 'fab fa-invision', 'f7b0', 'brands'),
(1216, 'Ioxhost', 'fab fa-ioxhost', 'f208', 'brands'),
(1217, 'Itch Io', 'fab fa-itch-io', 'f83a', 'brands'),
(1218, 'Itunes', 'fab fa-itunes', 'f3b4', 'brands'),
(1219, 'Itunes Note', 'fab fa-itunes-note', 'f3b5', 'brands'),
(1220, 'Java', 'fab fa-java', 'f4e4', 'brands'),
(1221, 'Jedi Order', 'fab fa-jedi-order', 'f50e', 'brands'),
(1222, 'Jenkins', 'fab fa-jenkins', 'f3b6', 'brands'),
(1223, 'Jira', 'fab fa-jira', 'f7b1', 'brands'),
(1224, 'Joget', 'fab fa-joget', 'f3b7', 'brands'),
(1225, 'Joomla', 'fab fa-joomla', 'f1aa', 'brands'),
(1226, 'Js', 'fab fa-js', 'f3b8', 'brands'),
(1227, 'Js Square', 'fab fa-js-square', 'f3b9', 'brands'),
(1228, 'Jsfiddle', 'fab fa-jsfiddle', 'f1cc', 'brands'),
(1229, 'Kaggle', 'fab fa-kaggle', 'f5fa', 'brands'),
(1230, 'Keybase', 'fab fa-keybase', 'f4f5', 'brands'),
(1231, 'Keycdn', 'fab fa-keycdn', 'f3ba', 'brands'),
(1232, 'Kickstarter', 'fab fa-kickstarter', 'f3bb', 'brands'),
(1233, 'Kickstarter K', 'fab fa-kickstarter-k', 'f3bc', 'brands'),
(1234, 'Korvue', 'fab fa-korvue', 'f42f', 'brands'),
(1235, 'Laravel', 'fab fa-laravel', 'f3bd', 'brands'),
(1236, 'Lastfm', 'fab fa-lastfm', 'f202', 'brands'),
(1237, 'Lastfm Square', 'fab fa-lastfm-square', 'f203', 'brands'),
(1238, 'Leanpub', 'fab fa-leanpub', 'f212', 'brands'),
(1239, 'Less', 'fab fa-less', 'f41d', 'brands'),
(1240, 'Line', 'fab fa-line', 'f3c0', 'brands'),
(1241, 'Linkedin', 'fab fa-linkedin', 'f08c', 'brands'),
(1242, 'Linkedin In', 'fab fa-linkedin-in', 'f0e1', 'brands'),
(1243, 'Linode', 'fab fa-linode', 'f2b8', 'brands'),
(1244, 'Linux', 'fab fa-linux', 'f17c', 'brands'),
(1245, 'Lyft', 'fab fa-lyft', 'f3c3', 'brands'),
(1246, 'Magento', 'fab fa-magento', 'f3c4', 'brands'),
(1247, 'Mailchimp', 'fab fa-mailchimp', 'f59e', 'brands'),
(1248, 'Mandalorian', 'fab fa-mandalorian', 'f50f', 'brands'),
(1249, 'Markdown', 'fab fa-markdown', 'f60f', 'brands'),
(1250, 'Mastodon', 'fab fa-mastodon', 'f4f6', 'brands'),
(1251, 'Maxcdn', 'fab fa-maxcdn', 'f136', 'brands'),
(1252, 'Mdb', 'fab fa-mdb', 'f8ca', 'brands'),
(1253, 'Medapps', 'fab fa-medapps', 'f3c6', 'brands'),
(1254, 'Medium', 'fab fa-medium', 'f23a', 'brands'),
(1255, 'Medium M', 'fab fa-medium-m', 'f3c7', 'brands'),
(1256, 'Medrt', 'fab fa-medrt', 'f3c8', 'brands'),
(1257, 'Meetup', 'fab fa-meetup', 'f2e0', 'brands'),
(1258, 'Megaport', 'fab fa-megaport', 'f5a3', 'brands'),
(1259, 'Mendeley', 'fab fa-mendeley', 'f7b3', 'brands'),
(1260, 'Microblog', 'fab fa-microblog', 'e01a', 'brands'),
(1261, 'Microsoft', 'fab fa-microsoft', 'f3ca', 'brands'),
(1262, 'Mix', 'fab fa-mix', 'f3cb', 'brands'),
(1263, 'Mixcloud', 'fab fa-mixcloud', 'f289', 'brands'),
(1264, 'Mixer', 'fab fa-mixer', 'e056', 'brands'),
(1265, 'Mizuni', 'fab fa-mizuni', 'f3cc', 'brands'),
(1266, 'Modx', 'fab fa-modx', 'f285', 'brands'),
(1267, 'Monero', 'fab fa-monero', 'f3d0', 'brands'),
(1268, 'Napster', 'fab fa-napster', 'f3d2', 'brands'),
(1269, 'Neos', 'fab fa-neos', 'f612', 'brands'),
(1270, 'Nimblr', 'fab fa-nimblr', 'f5a8', 'brands'),
(1271, 'Node', 'fab fa-node', 'f419', 'brands'),
(1272, 'Node Js', 'fab fa-node-js', 'f3d3', 'brands'),
(1273, 'Npm', 'fab fa-npm', 'f3d4', 'brands'),
(1274, 'Ns8', 'fab fa-ns8', 'f3d5', 'brands'),
(1275, 'Nutritionix', 'fab fa-nutritionix', 'f3d6', 'brands'),
(1276, 'Octopus Deploy', 'fab fa-octopus-deploy', 'e082', 'brands'),
(1277, 'Odnoklassniki', 'fab fa-odnoklassniki', 'f263', 'brands'),
(1278, 'Odnoklassniki Square', 'fab fa-odnoklassniki-square', 'f264', 'brands'),
(1279, 'Old Republic', 'fab fa-old-republic', 'f510', 'brands'),
(1280, 'Opencart', 'fab fa-opencart', 'f23d', 'brands'),
(1281, 'Openid', 'fab fa-openid', 'f19b', 'brands'),
(1282, 'Opera', 'fab fa-opera', 'f26a', 'brands'),
(1283, 'Optin Monster', 'fab fa-optin-monster', 'f23c', 'brands'),
(1284, 'Orcid', 'fab fa-orcid', 'f8d2', 'brands'),
(1285, 'Osi', 'fab fa-osi', 'f41a', 'brands'),
(1286, 'Page4', 'fab fa-page4', 'f3d7', 'brands'),
(1287, 'Pagelines', 'fab fa-pagelines', 'f18c', 'brands'),
(1288, 'Palfed', 'fab fa-palfed', 'f3d8', 'brands'),
(1289, 'Patreon', 'fab fa-patreon', 'f3d9', 'brands'),
(1290, 'Paypal', 'fab fa-paypal', 'f1ed', 'brands'),
(1291, 'Penny Arcade', 'fab fa-penny-arcade', 'f704', 'brands'),
(1292, 'Perbyte', 'fab fa-perbyte', 'e083', 'brands'),
(1293, 'Periscope', 'fab fa-periscope', 'f3da', 'brands'),
(1294, 'Phabricator', 'fab fa-phabricator', 'f3db', 'brands'),
(1295, 'Phoenix Framework', 'fab fa-phoenix-framework', 'f3dc', 'brands'),
(1296, 'Phoenix Squadron', 'fab fa-phoenix-squadron', 'f511', 'brands'),
(1297, 'Php', 'fab fa-php', 'f457', 'brands'),
(1298, 'Pied Piper', 'fab fa-pied-piper', 'f2ae', 'brands'),
(1299, 'Pied Piper Alt', 'fab fa-pied-piper-alt', 'f1a8', 'brands'),
(1300, 'Pied Piper Hat', 'fab fa-pied-piper-hat', 'f4e5', 'brands'),
(1301, 'Pied Piper Pp', 'fab fa-pied-piper-pp', 'f1a7', 'brands'),
(1302, 'Pied Piper Square', 'fab fa-pied-piper-square', 'e01e', 'brands'),
(1303, 'Pinterest', 'fab fa-pinterest', 'f0d2', 'brands'),
(1304, 'Pinterest P', 'fab fa-pinterest-p', 'f231', 'brands'),
(1305, 'Pinterest Square', 'fab fa-pinterest-square', 'f0d3', 'brands'),
(1306, 'Playstation', 'fab fa-playstation', 'f3df', 'brands'),
(1307, 'Product Hunt', 'fab fa-product-hunt', 'f288', 'brands'),
(1308, 'Pushed', 'fab fa-pushed', 'f3e1', 'brands'),
(1309, 'Python', 'fab fa-python', 'f3e2', 'brands'),
(1310, 'Qq', 'fab fa-qq', 'f1d6', 'brands'),
(1311, 'Quinscape', 'fab fa-quinscape', 'f459', 'brands'),
(1312, 'Quora', 'fab fa-quora', 'f2c4', 'brands'),
(1313, 'R Project', 'fab fa-r-project', 'f4f7', 'brands'),
(1314, 'Raspberry Pi', 'fab fa-raspberry-pi', 'f7bb', 'brands'),
(1315, 'Ravelry', 'fab fa-ravelry', 'f2d9', 'brands'),
(1316, 'React', 'fab fa-react', 'f41b', 'brands'),
(1317, 'Reacteurope', 'fab fa-reacteurope', 'f75d', 'brands'),
(1318, 'Readme', 'fab fa-readme', 'f4d5', 'brands'),
(1319, 'Rebel', 'fab fa-rebel', 'f1d0', 'brands'),
(1320, 'Red River', 'fab fa-red-river', 'f3e3', 'brands'),
(1321, 'Reddit', 'fab fa-reddit', 'f1a1', 'brands'),
(1322, 'Reddit Alien', 'fab fa-reddit-alien', 'f281', 'brands'),
(1323, 'Reddit Square', 'fab fa-reddit-square', 'f1a2', 'brands'),
(1324, 'Redhat', 'fab fa-redhat', 'f7bc', 'brands'),
(1325, 'Renren', 'fab fa-renren', 'f18b', 'brands'),
(1326, 'Replyd', 'fab fa-replyd', 'f3e6', 'brands'),
(1327, 'Researchgate', 'fab fa-researchgate', 'f4f8', 'brands'),
(1328, 'Resolving', 'fab fa-resolving', 'f3e7', 'brands'),
(1329, 'Rev', 'fab fa-rev', 'f5b2', 'brands'),
(1330, 'Rocketchat', 'fab fa-rocketchat', 'f3e8', 'brands'),
(1331, 'Rockrms', 'fab fa-rockrms', 'f3e9', 'brands'),
(1332, 'Rust', 'fab fa-rust', 'e07a', 'brands'),
(1333, 'Safari', 'fab fa-safari', 'f267', 'brands'),
(1334, 'Salesforce', 'fab fa-salesforce', 'f83b', 'brands'),
(1335, 'Sass', 'fab fa-sass', 'f41e', 'brands'),
(1336, 'Schlix', 'fab fa-schlix', 'f3ea', 'brands'),
(1337, 'Scribd', 'fab fa-scribd', 'f28a', 'brands'),
(1338, 'Searchengin', 'fab fa-searchengin', 'f3eb', 'brands'),
(1339, 'Sellcast', 'fab fa-sellcast', 'f2da', 'brands'),
(1340, 'Sellsy', 'fab fa-sellsy', 'f213', 'brands'),
(1341, 'Servicestack', 'fab fa-servicestack', 'f3ec', 'brands'),
(1342, 'Shirtsinbulk', 'fab fa-shirtsinbulk', 'f214', 'brands'),
(1343, 'Shopify', 'fab fa-shopify', 'e057', 'brands'),
(1344, 'Shopware', 'fab fa-shopware', 'f5b5', 'brands'),
(1345, 'Simplybuilt', 'fab fa-simplybuilt', 'f215', 'brands'),
(1346, 'Sistrix', 'fab fa-sistrix', 'f3ee', 'brands'),
(1347, 'Sith', 'fab fa-sith', 'f512', 'brands'),
(1348, 'Sketch', 'fab fa-sketch', 'f7c6', 'brands'),
(1349, 'Skyatlas', 'fab fa-skyatlas', 'f216', 'brands'),
(1350, 'Skype', 'fab fa-skype', 'f17e', 'brands'),
(1351, 'Slack', 'fab fa-slack', 'f198', 'brands'),
(1352, 'Slack Hash', 'fab fa-slack-hash', 'f3ef', 'brands'),
(1353, 'Slideshare', 'fab fa-slideshare', 'f1e7', 'brands'),
(1354, 'Snapchat', 'fab fa-snapchat', 'f2ab', 'brands'),
(1355, 'Snapchat Ghost', 'fab fa-snapchat-ghost', 'f2ac', 'brands'),
(1356, 'Snapchat Square', 'fab fa-snapchat-square', 'f2ad', 'brands'),
(1357, 'Soundcloud', 'fab fa-soundcloud', 'f1be', 'brands'),
(1358, 'Sourcetree', 'fab fa-sourcetree', 'f7d3', 'brands'),
(1359, 'Speakap', 'fab fa-speakap', 'f3f3', 'brands'),
(1360, 'Speaker Deck', 'fab fa-speaker-deck', 'f83c', 'brands'),
(1361, 'Spotify', 'fab fa-spotify', 'f1bc', 'brands'),
(1362, 'Squarespace', 'fab fa-squarespace', 'f5be', 'brands'),
(1363, 'Stack Exchange', 'fab fa-stack-exchange', 'f18d', 'brands'),
(1364, 'Stack Overflow', 'fab fa-stack-overflow', 'f16c', 'brands'),
(1365, 'Stackpath', 'fab fa-stackpath', 'f842', 'brands'),
(1366, 'Staylinked', 'fab fa-staylinked', 'f3f5', 'brands'),
(1367, 'Steam', 'fab fa-steam', 'f1b6', 'brands'),
(1368, 'Steam Square', 'fab fa-steam-square', 'f1b7', 'brands'),
(1369, 'Steam Symbol', 'fab fa-steam-symbol', 'f3f6', 'brands'),
(1370, 'Sticker Mule', 'fab fa-sticker-mule', 'f3f7', 'brands'),
(1371, 'Strava', 'fab fa-strava', 'f428', 'brands'),
(1372, 'Stripe', 'fab fa-stripe', 'f429', 'brands'),
(1373, 'Stripe S', 'fab fa-stripe-s', 'f42a', 'brands'),
(1374, 'Studiovinari', 'fab fa-studiovinari', 'f3f8', 'brands'),
(1375, 'Stumbleupon', 'fab fa-stumbleupon', 'f1a4', 'brands'),
(1376, 'Stumbleupon Circle', 'fab fa-stumbleupon-circle', 'f1a3', 'brands'),
(1377, 'Superpowers', 'fab fa-superpowers', 'f2dd', 'brands'),
(1378, 'Supple', 'fab fa-supple', 'f3f9', 'brands'),
(1379, 'Suse', 'fab fa-suse', 'f7d6', 'brands'),
(1380, 'Swift', 'fab fa-swift', 'f8e1', 'brands'),
(1381, 'Symfony', 'fab fa-symfony', 'f83d', 'brands'),
(1382, 'Teamspeak', 'fab fa-teamspeak', 'f4f9', 'brands'),
(1383, 'Telegram', 'fab fa-telegram', 'f2c6', 'brands'),
(1384, 'Telegram Plane', 'fab fa-telegram-plane', 'f3fe', 'brands'),
(1385, 'Tencent Weibo', 'fab fa-tencent-weibo', 'f1d5', 'brands'),
(1386, 'The Red Yeti', 'fab fa-the-red-yeti', 'f69d', 'brands'),
(1387, 'Themeco', 'fab fa-themeco', 'f5c6', 'brands'),
(1388, 'Themeisle', 'fab fa-themeisle', 'f2b2', 'brands'),
(1389, 'Think Peaks', 'fab fa-think-peaks', 'f731', 'brands'),
(1390, 'Tiktok', 'fab fa-tiktok', 'e07b', 'brands'),
(1391, 'Trade Federation', 'fab fa-trade-federation', 'f513', 'brands'),
(1392, 'Trello', 'fab fa-trello', 'f181', 'brands'),
(1393, 'Tripadvisor', 'fab fa-tripadvisor', 'f262', 'brands'),
(1394, 'Tumblr', 'fab fa-tumblr', 'f173', 'brands'),
(1395, 'Tumblr Square', 'fab fa-tumblr-square', 'f174', 'brands'),
(1396, 'Twitch', 'fab fa-twitch', 'f1e8', 'brands'),
(1397, 'Twitter', 'fab fa-twitter', 'f099', 'brands'),
(1398, 'Twitter Square', 'fab fa-twitter-square', 'f081', 'brands'),
(1399, 'Typo3', 'fab fa-typo3', 'f42b', 'brands'),
(1400, 'Uber', 'fab fa-uber', 'f402', 'brands'),
(1401, 'Ubuntu', 'fab fa-ubuntu', 'f7df', 'brands'),
(1402, 'Uikit', 'fab fa-uikit', 'f403', 'brands'),
(1403, 'Umbraco', 'fab fa-umbraco', 'f8e8', 'brands'),
(1404, 'Uncharted', 'fab fa-uncharted', 'e084', 'brands'),
(1405, 'Uniregistry', 'fab fa-uniregistry', 'f404', 'brands'),
(1406, 'Unity', 'fab fa-unity', 'e049', 'brands'),
(1407, 'Unsplash', 'fab fa-unsplash', 'e07c', 'brands'),
(1408, 'Untappd', 'fab fa-untappd', 'f405', 'brands'),
(1409, 'Ups', 'fab fa-ups', 'f7e0', 'brands'),
(1410, 'Usb', 'fab fa-usb', 'f287', 'brands'),
(1411, 'Usps', 'fab fa-usps', 'f7e1', 'brands'),
(1412, 'Ussunnah', 'fab fa-ussunnah', 'f407', 'brands'),
(1413, 'Vaadin', 'fab fa-vaadin', 'f408', 'brands'),
(1414, 'Viacoin', 'fab fa-viacoin', 'f237', 'brands'),
(1415, 'Viadeo', 'fab fa-viadeo', 'f2a9', 'brands'),
(1416, 'Viadeo Square', 'fab fa-viadeo-square', 'f2aa', 'brands'),
(1417, 'Viber', 'fab fa-viber', 'f409', 'brands'),
(1418, 'Vimeo', 'fab fa-vimeo', 'f40a', 'brands'),
(1419, 'Vimeo Square', 'fab fa-vimeo-square', 'f194', 'brands'),
(1420, 'Vimeo V', 'fab fa-vimeo-v', 'f27d', 'brands'),
(1421, 'Vine', 'fab fa-vine', 'f1ca', 'brands'),
(1422, 'Vk', 'fab fa-vk', 'f189', 'brands'),
(1423, 'Vnv', 'fab fa-vnv', 'f40b', 'brands'),
(1424, 'Vuejs', 'fab fa-vuejs', 'f41f', 'brands'),
(1425, 'Watchman Monitoring', 'fab fa-watchman-monitoring', 'e087', 'brands'),
(1426, 'Waze', 'fab fa-waze', 'f83f', 'brands'),
(1427, 'Weebly', 'fab fa-weebly', 'f5cc', 'brands'),
(1428, 'Weibo', 'fab fa-weibo', 'f18a', 'brands'),
(1429, 'Weixin', 'fab fa-weixin', 'f1d7', 'brands'),
(1430, 'Whatsapp', 'fab fa-whatsapp', 'f232', 'brands'),
(1431, 'Whatsapp Square', 'fab fa-whatsapp-square', 'f40c', 'brands'),
(1432, 'Whmcs', 'fab fa-whmcs', 'f40d', 'brands'),
(1433, 'Wikipedia W', 'fab fa-wikipedia-w', 'f266', 'brands'),
(1434, 'Windows', 'fab fa-windows', 'f17a', 'brands'),
(1435, 'Wix', 'fab fa-wix', 'f5cf', 'brands'),
(1436, 'Wizards Of The Coast', 'fab fa-wizards-of-the-coast', 'f730', 'brands'),
(1437, 'Wodu', 'fab fa-wodu', 'e088', 'brands'),
(1438, 'Wolf Pack Battalion', 'fab fa-wolf-pack-battalion', 'f514', 'brands'),
(1439, 'Wordpress', 'fab fa-wordpress', 'f19a', 'brands'),
(1440, 'Wordpress Simple', 'fab fa-wordpress-simple', 'f411', 'brands'),
(1441, 'Wpbeginner', 'fab fa-wpbeginner', 'f297', 'brands'),
(1442, 'Wpexplorer', 'fab fa-wpexplorer', 'f2de', 'brands'),
(1443, 'Wpforms', 'fab fa-wpforms', 'f298', 'brands'),
(1444, 'Wpressr', 'fab fa-wpressr', 'f3e4', 'brands'),
(1445, 'Xbox', 'fab fa-xbox', 'f412', 'brands'),
(1446, 'Xing', 'fab fa-xing', 'f168', 'brands'),
(1447, 'Xing Square', 'fab fa-xing-square', 'f169', 'brands'),
(1448, 'Y Combinator', 'fab fa-y-combinator', 'f23b', 'brands'),
(1449, 'Yahoo', 'fab fa-yahoo', 'f19e', 'brands'),
(1450, 'Yammer', 'fab fa-yammer', 'f840', 'brands'),
(1451, 'Yandex', 'fab fa-yandex', 'f413', 'brands'),
(1452, 'Yandex International', 'fab fa-yandex-international', 'f414', 'brands'),
(1453, 'Yarn', 'fab fa-yarn', 'f7e3', 'brands'),
(1454, 'Yelp', 'fab fa-yelp', 'f1e9', 'brands'),
(1455, 'Yoast', 'fab fa-yoast', 'f2b1', 'brands'),
(1456, 'Youtube', 'fab fa-youtube', 'f167', 'brands'),
(1457, 'Youtube Square', 'fab fa-youtube-square', 'f431', 'brands'),
(1458, 'Zhihu', 'fab fa-zhihu', 'f63f', 'brands'),
(1459, 'Address Book', 'far fa-address-book', 'f2b9', 'regular'),
(1460, 'Address Card', 'far fa-address-card', 'f2bb', 'regular'),
(1461, 'Angry', 'far fa-angry', 'f556', 'regular'),
(1462, 'Arrow Alt Circle Down', 'far fa-arrow-alt-circle-down', 'f358', 'regular'),
(1463, 'Arrow Alt Circle Left', 'far fa-arrow-alt-circle-left', 'f359', 'regular'),
(1464, 'Arrow Alt Circle Right', 'far fa-arrow-alt-circle-right', 'f35a', 'regular'),
(1465, 'Arrow Alt Circle Up', 'far fa-arrow-alt-circle-up', 'f35b', 'regular'),
(1466, 'Bell', 'far fa-bell', 'f0f3', 'regular'),
(1467, 'Bell Slash', 'far fa-bell-slash', 'f1f6', 'regular'),
(1468, 'Bookmark', 'far fa-bookmark', 'f02e', 'regular'),
(1469, 'Building', 'far fa-building', 'f1ad', 'regular'),
(1470, 'Calendar', 'far fa-calendar', 'f133', 'regular'),
(1471, 'Calendar Alt', 'far fa-calendar-alt', 'f073', 'regular'),
(1472, 'Calendar Check', 'far fa-calendar-check', 'f274', 'regular'),
(1473, 'Calendar Minus', 'far fa-calendar-minus', 'f272', 'regular'),
(1474, 'Calendar Plus', 'far fa-calendar-plus', 'f271', 'regular'),
(1475, 'Calendar Times', 'far fa-calendar-times', 'f273', 'regular'),
(1476, 'Caret Square Down', 'far fa-caret-square-down', 'f150', 'regular'),
(1477, 'Caret Square Left', 'far fa-caret-square-left', 'f191', 'regular'),
(1478, 'Caret Square Right', 'far fa-caret-square-right', 'f152', 'regular'),
(1479, 'Caret Square Up', 'far fa-caret-square-up', 'f151', 'regular'),
(1480, 'Chart Bar', 'far fa-chart-bar', 'f080', 'regular'),
(1481, 'Check Circle', 'far fa-check-circle', 'f058', 'regular'),
(1482, 'Check Square', 'far fa-check-square', 'f14a', 'regular'),
(1483, 'Circle', 'far fa-circle', 'f111', 'regular'),
(1484, 'Clipboard', 'far fa-clipboard', 'f328', 'regular'),
(1485, 'Clock', 'far fa-clock', 'f017', 'regular'),
(1486, 'Clone', 'far fa-clone', 'f24d', 'regular'),
(1487, 'Closed Captioning', 'far fa-closed-captioning', 'f20a', 'regular'),
(1488, 'Comment', 'far fa-comment', 'f075', 'regular'),
(1489, 'Comment Alt', 'far fa-comment-alt', 'f27a', 'regular'),
(1490, 'Comment Dots', 'far fa-comment-dots', 'f4ad', 'regular'),
(1491, 'Comments', 'far fa-comments', 'f086', 'regular'),
(1492, 'Compass', 'far fa-compass', 'f14e', 'regular'),
(1493, 'Copy', 'far fa-copy', 'f0c5', 'regular'),
(1494, 'Copyright', 'far fa-copyright', 'f1f9', 'regular'),
(1495, 'Credit Card', 'far fa-credit-card', 'f09d', 'regular'),
(1496, 'Dizzy', 'far fa-dizzy', 'f567', 'regular'),
(1497, 'Dot Circle', 'far fa-dot-circle', 'f192', 'regular'),
(1498, 'Edit', 'far fa-edit', 'f044', 'regular'),
(1499, 'Envelope', 'far fa-envelope', 'f0e0', 'regular'),
(1500, 'Envelope Open', 'far fa-envelope-open', 'f2b6', 'regular'),
(1501, 'Eye', 'far fa-eye', 'f06e', 'regular'),
(1502, 'Eye Slash', 'far fa-eye-slash', 'f070', 'regular'),
(1503, 'File', 'far fa-file', 'f15b', 'regular'),
(1504, 'File Alt', 'far fa-file-alt', 'f15c', 'regular'),
(1505, 'File Archive', 'far fa-file-archive', 'f1c6', 'regular'),
(1506, 'File Audio', 'far fa-file-audio', 'f1c7', 'regular'),
(1507, 'File Code', 'far fa-file-code', 'f1c9', 'regular'),
(1508, 'File Excel', 'far fa-file-excel', 'f1c3', 'regular'),
(1509, 'File Image', 'far fa-file-image', 'f1c5', 'regular'),
(1510, 'File Pdf', 'far fa-file-pdf', 'f1c1', 'regular'),
(1511, 'File Powerpoint', 'far fa-file-powerpoint', 'f1c4', 'regular'),
(1512, 'File Video', 'far fa-file-video', 'f1c8', 'regular'),
(1513, 'File Word', 'far fa-file-word', 'f1c2', 'regular'),
(1514, 'Flag', 'far fa-flag', 'f024', 'regular'),
(1515, 'Flushed', 'far fa-flushed', 'f579', 'regular'),
(1516, 'Folder', 'far fa-folder', 'f07b', 'regular'),
(1517, 'Folder Open', 'far fa-folder-open', 'f07c', 'regular'),
(1518, 'Frown', 'far fa-frown', 'f119', 'regular'),
(1519, 'Frown Open', 'far fa-frown-open', 'f57a', 'regular'),
(1520, 'Futbol', 'far fa-futbol', 'f1e3', 'regular'),
(1521, 'Gem', 'far fa-gem', 'f3a5', 'regular'),
(1522, 'Grimace', 'far fa-grimace', 'f57f', 'regular'),
(1523, 'Grin', 'far fa-grin', 'f580', 'regular'),
(1524, 'Grin Alt', 'far fa-grin-alt', 'f581', 'regular'),
(1525, 'Grin Beam', 'far fa-grin-beam', 'f582', 'regular'),
(1526, 'Grin Beam Sweat', 'far fa-grin-beam-sweat', 'f583', 'regular'),
(1527, 'Grin Hearts', 'far fa-grin-hearts', 'f584', 'regular'),
(1528, 'Grin Squint', 'far fa-grin-squint', 'f585', 'regular'),
(1529, 'Grin Squint Tears', 'far fa-grin-squint-tears', 'f586', 'regular'),
(1530, 'Grin Stars', 'far fa-grin-stars', 'f587', 'regular'),
(1531, 'Grin Tears', 'far fa-grin-tears', 'f588', 'regular'),
(1532, 'Grin Tongue', 'far fa-grin-tongue', 'f589', 'regular'),
(1533, 'Grin Tongue Squint', 'far fa-grin-tongue-squint', 'f58a', 'regular'),
(1534, 'Grin Tongue Wink', 'far fa-grin-tongue-wink', 'f58b', 'regular'),
(1535, 'Grin Wink', 'far fa-grin-wink', 'f58c', 'regular'),
(1536, 'Hand Lizard', 'far fa-hand-lizard', 'f258', 'regular'),
(1537, 'Hand Paper', 'far fa-hand-paper', 'f256', 'regular'),
(1538, 'Hand Peace', 'far fa-hand-peace', 'f25b', 'regular'),
(1539, 'Hand Point Down', 'far fa-hand-point-down', 'f0a7', 'regular'),
(1540, 'Hand Point Left', 'far fa-hand-point-left', 'f0a5', 'regular'),
(1541, 'Hand Point Right', 'far fa-hand-point-right', 'f0a4', 'regular'),
(1542, 'Hand Point Up', 'far fa-hand-point-up', 'f0a6', 'regular'),
(1543, 'Hand Pointer', 'far fa-hand-pointer', 'f25a', 'regular'),
(1544, 'Hand Rock', 'far fa-hand-rock', 'f255', 'regular'),
(1545, 'Hand Scissors', 'far fa-hand-scissors', 'f257', 'regular'),
(1546, 'Hand Spock', 'far fa-hand-spock', 'f259', 'regular'),
(1547, 'Handshake', 'far fa-handshake', 'f2b5', 'regular'),
(1548, 'Hdd', 'far fa-hdd', 'f0a0', 'regular'),
(1549, 'Heart', 'far fa-heart', 'f004', 'regular'),
(1550, 'Hospital', 'far fa-hospital', 'f0f8', 'regular'),
(1551, 'Hourglass', 'far fa-hourglass', 'f254', 'regular'),
(1552, 'Id Badge', 'far fa-id-badge', 'f2c1', 'regular'),
(1553, 'Id Card', 'far fa-id-card', 'f2c2', 'regular'),
(1554, 'Image', 'far fa-image', 'f03e', 'regular'),
(1555, 'Images', 'far fa-images', 'f302', 'regular'),
(1556, 'Keyboard', 'far fa-keyboard', 'f11c', 'regular'),
(1557, 'Kiss', 'far fa-kiss', 'f596', 'regular'),
(1558, 'Kiss Beam', 'far fa-kiss-beam', 'f597', 'regular'),
(1559, 'Kiss Wink Heart', 'far fa-kiss-wink-heart', 'f598', 'regular'),
(1560, 'Laugh', 'far fa-laugh', 'f599', 'regular'),
(1561, 'Laugh Beam', 'far fa-laugh-beam', 'f59a', 'regular'),
(1562, 'Laugh Squint', 'far fa-laugh-squint', 'f59b', 'regular'),
(1563, 'Laugh Wink', 'far fa-laugh-wink', 'f59c', 'regular'),
(1564, 'Lemon', 'far fa-lemon', 'f094', 'regular'),
(1565, 'Life Ring', 'far fa-life-ring', 'f1cd', 'regular'),
(1566, 'Lightbulb', 'far fa-lightbulb', 'f0eb', 'regular'),
(1567, 'List Alt', 'far fa-list-alt', 'f022', 'regular'),
(1568, 'Map', 'far fa-map', 'f279', 'regular'),
(1569, 'Meh', 'far fa-meh', 'f11a', 'regular'),
(1570, 'Meh Blank', 'far fa-meh-blank', 'f5a4', 'regular'),
(1571, 'Meh Rolling Eyes', 'far fa-meh-rolling-eyes', 'f5a5', 'regular'),
(1572, 'Minus Square', 'far fa-minus-square', 'f146', 'regular'),
(1573, 'Money Bill Alt', 'far fa-money-bill-alt', 'f3d1', 'regular'),
(1574, 'Moon', 'far fa-moon', 'f186', 'regular'),
(1575, 'Newspaper', 'far fa-newspaper', 'f1ea', 'regular'),
(1576, 'Object Group', 'far fa-object-group', 'f247', 'regular'),
(1577, 'Object Ungroup', 'far fa-object-ungroup', 'f248', 'regular'),
(1578, 'Paper Plane', 'far fa-paper-plane', 'f1d8', 'regular'),
(1579, 'Pause Circle', 'far fa-pause-circle', 'f28b', 'regular'),
(1580, 'Play Circle', 'far fa-play-circle', 'f144', 'regular'),
(1581, 'Plus Square', 'far fa-plus-square', 'f0fe', 'regular'),
(1582, 'Question Circle', 'far fa-question-circle', 'f059', 'regular'),
(1583, 'Registered', 'far fa-registered', 'f25d', 'regular'),
(1584, 'Sad Cry', 'far fa-sad-cry', 'f5b3', 'regular'),
(1585, 'Sad Tear', 'far fa-sad-tear', 'f5b4', 'regular'),
(1586, 'Save', 'far fa-save', 'f0c7', 'regular'),
(1587, 'Share Square', 'far fa-share-square', 'f14d', 'regular'),
(1588, 'Smile', 'far fa-smile', 'f118', 'regular'),
(1589, 'Smile Beam', 'far fa-smile-beam', 'f5b8', 'regular'),
(1590, 'Smile Wink', 'far fa-smile-wink', 'f4da', 'regular'),
(1591, 'Snowflake', 'far fa-snowflake', 'f2dc', 'regular'),
(1592, 'Square', 'far fa-square', 'f0c8', 'regular'),
(1593, 'Star', 'far fa-star', 'f005', 'regular'),
(1594, 'Star Half', 'far fa-star-half', 'f089', 'regular'),
(1595, 'Sticky Note', 'far fa-sticky-note', 'f249', 'regular'),
(1596, 'Stop Circle', 'far fa-stop-circle', 'f28d', 'regular'),
(1597, 'Sun', 'far fa-sun', 'f185', 'regular'),
(1598, 'Surprise', 'far fa-surprise', 'f5c2', 'regular'),
(1599, 'Thumbs Down', 'far fa-thumbs-down', 'f165', 'regular'),
(1600, 'Thumbs Up', 'far fa-thumbs-up', 'f164', 'regular'),
(1601, 'Times Circle', 'far fa-times-circle', 'f057', 'regular'),
(1602, 'Tired', 'far fa-tired', 'f5c8', 'regular'),
(1603, 'Trash Alt', 'far fa-trash-alt', 'f2ed', 'regular'),
(1604, 'User', 'far fa-user', 'f007', 'regular'),
(1605, 'User Circle', 'far fa-user-circle', 'f2bd', 'regular'),
(1606, 'Window Close', 'far fa-window-close', 'f410', 'regular'),
(1607, 'Window Maximize', 'far fa-window-maximize', 'f2d0', 'regular'),
(1608, 'Window Minimize', 'far fa-window-minimize', 'f2d1', 'regular'),
(1609, 'Window Restore', 'far fa-window-restore', 'f2d2', 'regular');

INSERT INTO `_menu_modul` (`id`, `label`, `parent`, `icon_class_id`, `modul`, `urutan`, `status`, `keterangan`) VALUES
(1, 'System Access', 0, 941, '#', 1, '1', ''),
(2, 'Daftar Menu', 1, 533, 'menu', 1, '1', ''),
(3, 'Akses Modul', 1, 923, 'hak_akses', 2, '1', ''),
(4, 'Aksi View', 1, 309, 'hak_aksi', 3, '1', ''),
(5, 'Dashboard', 0, 467, 'home', 0, '1', ''),
(6, 'Manajemen User', 1, 953, 'user', 4, '1', ''),
(7, 'Role User', 1, 1604, 'role', 5, '1', '');


-- --------------------------------------------------------
INSERT INTO `_modul_akses` (`id`, `id_role`, `id_menu`) VALUES
(1, 1, 1),
(2, 1, 2),
(3, 1, 3),
(4, 1, 4),
(5, 1, 5),
(6, 1, 6),
(7, 1, 7);


INSERT INTO `_modul_aksi` (`id`, `id_akses`, `input`, `edit`, `view`, `delete`, `deleteall`, `load`, `export`, `print`, `view_page`) VALUES
(1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 'V_index'),
(2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 'V_index'),
(4, 4, 1, 1, 1, 1, 0, 1, 1, 1, 'V_index');

